### ISSUE TITLE
Shortcut: [CUSTOM:YourFieldName]

### ISSUE THREAD

**Issue by jmchauvel** [akeeba/akeebasubs#100]
Nikos,

I have the following custom field NAME declared for multilingual support:
COM_AKEEBASUBS_LEVEL_FIELD_COMPANY_PHONENUMBER

When using in Emails the [CUSTOM:YourFieldName], eg:
[CUSTOM:COM_AKEEBASUBS_LEVEL_FIELD_COMPANY_PHONENUMBER]
it is not being replaced.

**Comment by nikosdion** [comment]
Not an issue. Read the documentation.

**Comment by jmchauvel** [comment]
Nikos, before writing, I did!
https://www.akeebabackup.com/documentation/akeeba-subscriptions/custom-fields.html
Documentation mentions:
...as described in our translation instructions below.
But there are no instructions! All links including on the main subscription page (https://www.akeebabackup.com/documentation/akeeba-subscriptions/akeeba-subscriptions.html) are pointing to ../custom-fields.html

**Comment by nikosdion** [comment]
In the [CUSTOM:SOMETHING] variable construct the "something" is the slug (alias) of the custom field, NOT the language string key you are using to translate its visible label in the front-end. 

From the documentation page you linked to:

> You can use custom field data in a Subscription Level's sign-up and cancellation messages. Assuming that your custom field's slug is my_field you can use the merge tag [CUSTOM:MY_FIELD] to access your custom field's contents. Please note that despite the case (lower or upper case) you've used for the slug you have to type the merge tag in all uppercase letters.

**Comment by jmchauvel** [comment]
Thank you Nikos.
