### ISSUE TITLE
In subscriptions view: Level name getting not translated

### ISSUE THREAD

**Issue by jmchauvel** [akeeba/akeebasubs#101]
In component/frontend/views/subscriptions/tmpl/default.php
<?php echo $this->escape($subscription->title)?>
does not get localized version of the Level title.

It is displaying translated version when replaced with:
<?php echo $this->escape($level->title)?>

**Comment by nikosdion** [comment]
Can you please submit a pull request with your suggestion?

**Comment by jmchauvel** [comment]
I hope I did it the right way, not used to github yet!
