### ISSUE TITLE
Akeeba Subs sends out hundres of emails per day to 1 person

### ISSUE THREAD

**Issue by spignataro** [akeeba/akeebasubs#104]
We have been receiving reports from individuals that they where receiving hundreds of emails from us. We thought it was a issues with our server so we moved the sending of our email to google mail. The results ended up being the same and maxing out our sending limit.

I havn't quite nailed down the issue in the code - but it is a real problem that does need to be addressed and I am almost certain that other are effected by this bug as well.

![screen shot 2015-01-08 at 6 52 13 am](https://cloud.githubusercontent.com/assets/72186/5662298/4d5793e0-9705-11e4-9ef3-e68b7fa1e9ff.png)

**Comment by nikosdion** [comment]
It is not a bug. You have bad data in your database, presumably from a bad import. Make sure the #__akeebasubs_subscriptions table has the contact_flag, first_contact, second_contact and after_contact flags. Make sure the contact_flag for expired subscriptions is set to 3 and both first_contact and second_contact have dates in the past.

**Comment by spignataro** [comment]
I updated the contact_flag to be 3. Should I do anything about the dates not being set? Or will it now just send out 3 times?

**Comment by nikosdion** [comment]
You don't have to do anything else. contact_flag = 3 means "do not send out any more emails".
