### ISSUE TITLE
Upgrade rules 'Max. Presence' validation

### ISSUE THREAD

**Issue by photodude** [akeeba/akeebasubs#106]
the Upgrade rules 'Max. Presence' field can exceed the subscription length of the ‘From Level’.
This may be something for validation consideration.
In testing I was not able to determine if a 'Max. Presence' which exceeds the subscription length of the ‘From Level’ causes any issues with upgrade discounts.

**Comment by nikosdion** [comment]
This is by design. Think about when you have manually extended a user's subscription beyond the nominal length of the subscription level. It happens to us all the time.

**Comment by photodude** [comment]
good point, especially since you can use custom fields to "extended a user's subscription beyond the nominal length"
