### ISSUE TITLE
Documentation issue - Paypal Payments Pro and Paypal Payments Pro (Express Checkout)

### ISSUE THREAD

**Issue by photodude** [akeeba/akeebasubs#111]
The references in the documentation that go to Paypal Payments Pro and Paypal Payments Pro (Express Checkout) redirect to Paypal. 
https://www.akeebabackup.com/documentation/akeeba-subscriptions/plugins-payment.html 

These plugins still exist in the project indicating a possible issue with the documentation.

**Comment by nikosdion** [comment]
I can see what is going on, but I can’t fix it without breaking other URLs :(=

**Comment by nikosdion** [comment]
Fixed on our site. The issue had to do with DocImport's parsing of page aliases.
