### ISSUE TITLE
akeeba 4.1 subsriptions custom field ain't working

### ISSUE THREAD

**Issue by fvissers** [akeeba/akeebasubs#113]
when i make a dutch custom field for example bedrijf
the custom field is showing by registration but when push the button it aint going further.
then it says you have to fill that custom field 

so it stoks. when you install a older version it works

the same for vatnumber, i will have the vatnumber within the registraion when the subscriber comes frome the Netherlands. it stil get empty what i do it aint working

**Comment by nikosdion** [comment]
The language of the field's label or name is irrelevant. You can name your field asjkhdfgadskjhfgeqk and it will still work. Check your field's setup.
