### ISSUE TITLE
Custom Email templates dont seem to work

### ISSUE THREAD

**Issue by parthlawate** [akeeba/akeebasubs#115]
Hi, 

The custom email templates as described here : https://www.akeebabackup.com/documentation/akeeba-subscriptions/email-templates.html dont seem to work. I was planning to use them to send out additional emails after the user subscription is activated. A sort of Welcome email on a per product basis with some product education included. But it seems the new email configured is not going out at all.. 

Does that mean that you can only create one template for one specific trigger ? Is this expected behavior.. Planning to dive into code but wanted to check if anyone else has seen the same thing ..

Parth

**Comment by nikosdion** [comment]
It does work. I know because we use them for the very same reason you want to use them. I know these messages are sent since I can see them in Mandrill.

Please remember that email templates are applied from most specific to least specific. Create a template for the exact subscription level and language (or UK English, not US English).

**Comment by parthlawate** [comment]
Ok. I wil try and figure out what i am doing wrong then. Right now i had a template setup for a specific subscription and Languages set to ALL.  Note that when i test i am using the 'Send test email' button .. An email is set out .. But that's a general activation email for one of the subscriptions i have.. Not the new one i made. Is there a chance the bug is with the test email function then ?

**Comment by nikosdion** [comment]
It could be.

**Comment by parthlawate** [comment]
If i configure multiple emails at the same rule ( Subscription Activated) will it exit after sending the first email it finds ( coming from most specific to least specific) or will it continue to send any other emails it finds ? The behavior i am seeing is that the less specific email ( applying to all subscriptions) is actually sent.. But the specific one to one subscription is not sent.. 

Just confirmed that this is happening on actual subscriptions. And the test email definitely has a bug. Will try and get in a patch for that one and propose a alternate workflow for the test email to work..

**Comment by nikosdion** [comment]
It will send the first email it finds that matches the criteria. That's
what we have the ordering for. Order the most specific (specific
subscription level) first, generic catch-all emails last.

If you submit a PR for the test email feature it will be accepted. If you
submit a PR for the email template finder algorithm it will be rejected (I
don't want to screw up my site).
