### ISSUE TITLE
Need age verification plugin for akeeba subscriptions

### ISSUE THREAD

**Issue by peri0603** [akeeba/akeebasubs#117]
P.S. Using currently the latest (4.1.1).

**Comment by nikosdion** [comment]
This plugin was removed in 4.0.0.

**Comment by peri0603** [comment]
Do you plan to reintegrate it or should i you the latest 3.x...

**Comment by peri0603** [comment]
Till it comes out with the 4.x branch

**Comment by nikosdion** [comment]
No plan to integrate anything, no plan to support 3.x.

**Comment by peri0603** [comment]
ok but akeeba subs. is now opensource???

**Comment by peri0603** [comment]
when it's on github???

**Comment by nikosdion** [comment]
It has ALWAYS been licensed under the GNU GPL v3. Please read https://www.gnu.org/philosophy/free-sw.html for an explanation of your rights under the GPL. So, the software is on GitHub and you're very welcome to fork the repository and modify its source code as you see fit (freedom #1), use it for whatever purpose you want (freedom #0), distribute copies of the software (freedom #2) and even distribute copies of your modified version under the same license (freedom #3). Also note that nowhere does it say that the developer is your unpaid slave. OK? The code is here, YOU can modify it as YOU wish, by YOURSELF. That's what Free and Open Source Software means.

**Comment by peri0603** [comment]
ok thanx... i have forgotten that is released under GNU GPL v3...

**Comment by peri0603** [comment]
But i'am not a programmer...

**Comment by peri0603** [comment]
i'am just a computer nerd

**Comment by nikosdion** [comment]
And I am a developer, not a slave. This issue is locked. Please refrain from filing any more issues. The idea behind having a GitHub repository is for DEVELOPERS to submit features and bug fixes, NOT for end users demanding support and/or customisations.
