### ISSUE TITLE
4.x install issue

### ISSUE THREAD

**Issue by thinkerytim** [akeeba/akeebasubs#121]
Hi Nick-- just did a fresh build / install of the akeebasubs 4.x branch on a new Joomla 3.4 install (no previous install of Akeeba) and failed to install with the following error:

Warning
Table 'joomla3.jos_akeebasubs_upgrades' doesn't exist SQL=SHOW FULL COLUMNS FROM `jos_akeebasubs_upgrades`

I did a pull / build / phing git to the fof package prior to building the new akeebasubs package. 

Any ideas?

**Comment by nikosdion** [comment]
Besides the warning, did it install? I see that we do try to create this table somewhere in the middle of the schema XML file. I don't see how you can get an error for this table only.

**Comment by thinkerytim** [comment]
No, the install failed.

Tim Kramer
tim@thethinkery.net
The Thinkery, LLC

**Comment by nikosdion** [comment]
I just pushed the fix in the 4.x branch. There was a comma missing.

**Comment by thinkerytim** [comment]
Thanks Nick-- that resolved it.
