### ISSUE TITLE
PayPal Surcharge not applying correctly when Subscription option field is selected

### ISSUE THREAD

**Issue by spfaehler** [akeeba/akeebasubs#122]
I have a custom subscription option field that adds $300 to my subscription base of $250.  When I select the paypal button without the subscription option, the 3% surcharge is correctly added to the total due.  When I select the subscription option, the price changes as it should, but the surcharge is not re-calculated based on the new total.  Is this feature functioning "as expected"? OR should it be re-calculating the surcharge?

Joomla v3.4
Akeeba Subs v4.2
Paypal Plugin v1.0

**Comment by nikosdion** [comment]
Works as expected as you can read in the code.

Also please note that support has been *TERMINATED* since November 2013.
