### ISSUE TITLE
Slave subscriptions added from administrator interface are not created

### ISSUE THREAD

**Issue by photodude** [akeeba/akeebasubs#123]
Slave subscriptions added to a "master" subscription from administrator interface are not created.
(tested against version 4.2.1, Joomla 3.4.0)

Steps to reproduce
1) Enable the Akeeba Subscriptions - Slave subscriptions support plugin
2) Create a subscription from the administrator interface for a subscription level that has at least Maximum slaves set to at least 1
3) reopen this new subscription, the option for "Add-on username #1" will now be available
4) enter a username to apply a slave subscription to, (save and close)
5) review the subscriptions, notice only the first subscription was created, no change happened on modification of the "master" subscription
6) click the "run integrations" button from the admin interface (since Salve subscriptions are listed as an integration plugin) 
7) review the subscriptions, notice: no change happened on "run integrations" no slave subscriptions applied to the master subscription were created.

Expected behavior, An addon user added from the front end or the administrator interface should create slave subscriptions identical to the "master" subscription.

**Comment by nikosdion** [comment]
No. This feature only works **when subscribing** (new subscription) and is only meant to be used in the front-end. Think about it. If you are an administrator it is perfectly possible for you to create the N+1 subscriptions and synchronise their expirations. In the front-end, a plain old user, not so much.

**Comment by photodude** [comment]
Ok, I can see that administrator it's possible to create the N+1 subscriptions.
Personally I think from a logistics stand point keeping the N+1 subscriptions linked and synced would be best as an automated process agnostic from the front end or the administrator interface.

**Comment by nikosdion** [comment]
The slave subscriptions feature is basically held together with string and duct tape. I know exactly what would be required to make it work as you might have imagined it should be working, but it's not worth the hassle. We'd have to make a very serious backwards compatibility break with everything that entails (including the possibility to lose subscriptions on upgrade, something I do NOT consider an option).

**Comment by photodude** [comment]
I'll have to talk to my team about what we might consider doing or contributing to this. I would agree that insuring that everything needs to continue to work is a must. Losing an important feature to add a minor feature, shouldn't be an option. 

We currently have a duct tape and shoe string solution to create an interface for akeeba subs to add an "account" level control (one account for multiple users to get the same time limited access over multiple subscription levels). This patch work solution has meet our needs up until now, since we have kept users out of the add/renew loop. We are now going to allow users to renew subscriptions; which has us reconsidering our patch work solution and making sure we are using as many built in features as possible.

**Comment by nikosdion** [comment]
Ideally you'd need Joomla! to support linked user accounts: when a change in one subscription's user groups occurs make the same change to the other accounts as well. In theory this should be possible with a custom component to provide the interface to the "parent" account and a user plugin to implement the user group synchronisation.

It does fall short on the need to log out and back in to make the new user group assignment effective. This is a problem that many of us tried to solve but it just either doesn't work properly or screws up the site's performance.

To the best of my knowledge this is a problem which cannot currently be solved in any elegant manner.

**Comment by photodude** [comment]
We were thinking of something kind of along those lines, but in the framework of linking/syncing the subscriptions. The "parent" subscription could store a list of add-on users and a list "child" subscription id's that were created for those add-on users when the "parent" subscription was saved. The "child" subscriptions would just store a flag indicating that it is a child and the subscription id of the "parent" subscription. 

From there I think some checks would be needed and a plugin to sync the child subscriptions when the parent was modified or renewed.

**Comment by nikosdion** [comment]
That's pretty much how the current implementation works. Well, look at the code. Maybe you'll have better luck than me.

**Comment by photodude** [comment]
Thank I'll see what we can come up with. So far the only thing I've noticed after looking at the code for plugins/akeebasubs/slavesubs/slavesubs.php and the subscriptions in the subscription table is during the function onAKSubscriptionChange; the params "slaveusers" is checked and stored in the table, but the "slavesubs_ids", although checked, does not seem to be stored in the database params when reviewing the subscription table.
