### ISSUE TITLE
Email templates not sending properly

### ISSUE THREAD

**Issue by caseyzman** [akeeba/akeebasubs#134]
I have email templates for my subscription levels and specified level and language on each. Even with the more specific parameters selected, the subscriber still receives the default "All Levels"/"All Languages" email template. When I disable the "All Levels" template, and only leave the more specific template published, the subscriber doesn't receive any email.

I've also noticed that the "Send test email" button doesn't work properly. Similar as described here: https://github.com/akeeba/akeebasubs/issues/115

When I click the "Send Test" Button, the email I receive is from a subscription level that was deleted long ago, and the template appears to be from the "All Levels" template.

**Comment by nikosdion** [comment]
Can't reproduce on current development branch

**Comment by caseyzman** [comment]
Hello,
Thank u for looking into this. I found my issue with the default emails being sent. I had a free subscription and had an assigned email template for the "subscription just got activated", however, it kept trying to send the "A new subscription just got paid" even though it was free. Anyways, the subscription emails work now

I never could get the test emails to work

And my issue with the deleted subscription must have been from my install over a previous build, Once I installed into a new database, it worked fine.

-Thanks again

**Comment by nikosdion** [comment]
You *are* getting the *correct* email type, however its wording is not suitable for *your* use case. Well, it's easy to fix that. You can create a new email template of the same type but only for the specific free subscription level and change its wording. That's the whole point for having email templates :)
