### ISSUE TITLE
subscription dates decrease on every save

### ISSUE THREAD

**Issue by photodude** [akeeba/akeebasubs#140]
replication steps
open an existing user subscription from the admin interface
repeatedly click save without making another changes. 
watch the dates (valid from, valid to, created date) all decrease by one day on every save.

**Comment by nikosdion** [comment]
I can't reproduce it, but I know what's the problem: your timezone. Try adding the time of the day in the Valid From/To subscriptions and this won't happen.

**Comment by photodude** [comment]
Added time of day, no change dates continue to decrease. 
Changed global time zone from Denver to UTC, no change dates continue to decrease.

**Comment by nikosdion** [comment]
Cannot reproduce.

For what it's worth, your created on date also saves. That would only make sense if it's a new record. I can't reproduce this with an existing record :(

**Comment by photodude** [comment]
It was a "recently created" subscription in AS5.
I'm testing with a fresh install, no subscriptions. 
create subscription on front end or from admin.
Immediately going to admin opening the subscription and clicking save several times.  
Maybe that's the difference. 
Testing against php 5.4 and MySQL 5.5
