### ISSUE TITLE
Install notices

### ISSUE THREAD

**Issue by photodude** [akeeba/akeebasubs#149]
Just did a fresh build of the current AS5 development with the updated F0F3 Development branch and I get the following messages in the admin panel and notices in the server error log.

![install isuue as5 revcfa39f9](https://cloud.githubusercontent.com/assets/10253980/7104135/2a303f1c-e088-11e4-84e9-697a4206ba78.PNG)

- PHP Notice:  Trying to get property of non-object in /administrator/modules/mod_akeebasubs/tmpl/default.php on line 85
- PHP Strict Standards:  Declaration of Com_AkeebasubsInstallerScript::renderPostUninstallation() should be compatible with FOF30\Utils\InstallScript::renderPostUninstallation($parent) in tmp/install_5529c0165c21d/install_5529c01b795b6/script.com_akeebasubs.php on line 32

**Comment by nikosdion** [comment]
For some reason Joomla! thinks it is an update, not a fresh install. Since the folders it's trying to delete are not there you get the warnings.

**Comment by nikosdion** [comment]
Also: I think you screwed up something in your build. If I'm right you must be missing Strapper.

**Comment by photodude** [comment]
I agree something is screwed up with this build. 

I checked for Strapper and it apparently is missing from my build even-though it was in my directory for the build. 

Looks like I'm going to have to start over and rebuilt everything again.

**Comment by nikosdion** [comment]
Have you checked out the Strapper repository <https://github.com/akeeba/strapper> into the "strapped" directory above the Akeeba Subs working copy root? Then you need to go into Akeeba Subs' build directory and run phing link and phing git to get the right package built.

**Comment by nikosdion** [comment]
Bloody autocorrect! It's "strapper", not "strapped".

**Comment by photodude** [comment]
Yep, I have a clone of the strapper repo in the "strapper" directory. 
I also have a build in the directory [zipme] Building ZIP: C:[path to github directory]\strapper\release\file_strapper30-rev6159B81-1427578952.zip

I've checked over things several times, everything is where it should be. All necessary repos for the build have been updated, linked and built. But strapper is apparently not making it into the akeebasubs build.

![image](https://cloud.githubusercontent.com/assets/10253980/7108781/51df9a06-e14d-11e4-9db8-bb8e51b063e4.png)

Looking over the build echo from the command line, I'm not finding a reference to strapper

# phing git
Buildfile: C:\[path2git]\akeebasubs\build\build.xml
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > new-release:
   [delete] Deleting directory C:\[path2git]\akeebasubs\release
    [mkdir] Created dir: C:\[path2git]\akeebasubs\release

AkeebaSubscriptions > setup-properties:

AkeebaSubscriptions > package-com:
     [copy] Copying 1 file to C:\[path2git]\akeebasubs\component
     [copy] Copying 1 file to C:\[path2git]\akeebasubs\component\backend
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\com_akeebasubs.zip

AkeebaSubscriptions > package-files:
     [copy] Copying 1 file to C:\[path2git]\akeebasubs\component\cli
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\file_akeebasubs.zip

AkeebaSubscriptions > package-modules:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-module-folder:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-module-item:
     [echo] Packaging module admin/akeebasubs
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\mod_akeebasubs.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-module-folder:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-module-item:
     [echo] Packaging module site/aksexpires
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\mod_aksexpires.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-module-item:
     [echo] Packaging module site/akslevels
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\mod_akslevels.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-module-item:
     [echo] Packaging module site/aksubslist
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\mod_aksubslist.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-module-item:
     [echo] Packaging module site/aktaxcountry
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\mod_aktaxcountry.zip

AkeebaSubscriptions > package-plugins:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-folder:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/adminemails
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_adminemails.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
    [echo] Packaging plugin akeebasubs/agreetoeu
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_agreetoeu.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/agreetotos
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_agreetotos.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/atscredits
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_atscredits.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/autocity
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_autocity.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/canalyticscommerce
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_canalyticscommerce.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/contentpublish
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_contentpublish.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/customfields
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_customfields.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/invoices
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_invoices.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/iproperty
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_iproperty.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/joomla
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_joomla.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/joomlaprofilesync
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_joomlaprofilesync.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/needslogout
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_needslogout.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/recaptcha
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_recaptcha.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/slavesubs
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_slavesubs.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/sql
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_sql.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/subscriptionemails
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_subscriptionemails.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akeebasubs/subscriptionemailsdebug
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akeebasubs_subscriptionemailsdebug.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-folder:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/2checkout
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_2checkout.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/2conew
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_2conew.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/none
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_none.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/offline
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_offline.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/paymill
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_paymill.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/paypal
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_paypal.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/paypalpaymentspro
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_paypalpaymentspro.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/paypalproexpress
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_paypalproexpress.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/skrill
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_skrill.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/stripe
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_stripe.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin akpayment/viva
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_akpayment_viva.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-folder:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin content/aslink
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_content_aslink.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin content/asrestricted
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_content_asrestricted.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin content/astimedrelease
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_content_astimedrelease.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-folder:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin system/as2cocollation
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_system_as2cocollation.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin system/asexpirationcontrol
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_system_asexpirationcontrol.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin system/asexpirationnotify
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_system_asexpirationnotify.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin system/aslogoutuser
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_system_aslogoutuser.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin system/asuserregredir
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_system_asuserregredir.zip
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-folder:
 [property] Loading C:\[path2git]\akeebasubs\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\akeebasubs\build\.\build.properties... skipped

AkeebaSubscriptions > package-plugin-item:
     [echo] Packaging plugin user/aslogoutuser
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\plg_user_aslogoutuser.zip

AkeebaSubscriptions > package-fof:
 [property] Loading C:\[path2git]\fof3\build\.\build.properties
 [property] Unable to find property file: C:\[path2git]\fof3\build\.\build.properties... skipped

FrameworkOnFramework > new-release:
   [delete] Deleting directory C:\[path2git]\fof3\release
    [mkdir] Created dir: C:\[path2git]\fof3\release

FrameworkOnFramework > setup-properties:
FrameworkOnFramework > library-package:

     [copy] Copying 1 file to C:\[path2git]\fof3
     [copy] Copying 1 file to C:\[path2git]\fof3\fof
     [copy] Copying 1 file to C:\[path2git]\fof3\fof
     [copy] Copying 1 file to C:\[path2git]\fof3\fof
    [zipme] Building ZIP: C:\[path2git]\fof3\release\lib_fof30-rev0CE1AFF-1428665250.zip
    [zipme] Building ZIP: C:\[path2git]\fof3\release\lib_fof30-rev0CE1AFF-1428665250.zip
    [zipme] Building ZIP: C:\[path2git]\fof3\release\lib_fof30-rev0CE1AFF-1428665250.zip
   [delete] Deleting 1 files from ..\..\fof3

FrameworkOnFramework > git:
     [copy] Copying 1 file to C:\[path2git]\akeebasubs\release

AkeebaSubscriptions > package-pkg:
     [copy] Copying 1 file to C:\[path2git]\akeebasubs\release
     [copy] Copying 1 file to C:\[path2git]\akeebasubs\release
     [copy] Copying 1 file to C:\[path2git]\akeebasubs\release
    [zipme] Building ZIP: C:\[path2git]\akeebasubs\release\pkg_akeebasubs-revCFA39F9.zip
   [delete] Deleting 49 files from ..\release

AkeebaSubscriptions > component-packages:
AkeebaSubscriptions > git:

BUILD FINISHED
Total time: 8.5363 seconds

**Comment by nikosdion** [comment]
I believe that with the changes I just pushed to the akeebasubs and strapper repositories this problem should be fixed. Can you pull the changes and give it another try?

**Comment by photodude** [comment]
Seems to be closer. I am now getting two JInstaller: :Install: Can't find XML setup file. notices.
attempting an uninstall gives the "JInstaller: :Install: Can't find XML setup file." and a Component Uninstall: Can't uninstall. Please remove manually.

Looking at the packages, the strapper install is ending up buried in an additional folder.

**Comment by photodude** [comment]
With the [PR I submitted for strapper] (https://github.com/akeeba/strapper/pull/1) and the other changes you made I believe this issue will be resolved.

**Comment by nikosdion** [comment]
I accepted your PR, it *should* work fine now.

**Comment by photodude** [comment]
I agree
