### ISSUE TITLE
Payment Off-line immediately activation problem

### ISSUE THREAD

**Issue by mino182** [akeeba/akeebasubs#151]
Hi, when I turn on "Activate subscription immediately" in off-line payment plugin, users are automatically activated only (he doesn't recieve email with activation link), but states of subscriptions are still pending, so their subscription aren't active. Is it possible to set this plugin to set status to completed automatically? Thanks.

Joomla 3.4.1, akeebasubs 4.2.1

**Comment by nikosdion** [comment]
We've stopped developing Akeeba Subs 4. All development effort has gone into AS5.
