### ISSUE TITLE
WARNING: Incompatible Akeeba Subscriptions plugin detected 

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#156]
Hey Nick,
I'm trying to test Akeebasubs 5 on my test site and update the plugins. I'm getting the following error on some pages:

>WARNING: Incompatible Akeeba Subscriptions plugin detected

>An outdated plugin was found in xxxx/libraries/cms/plugin/helper.php which is incompatible with Akeeba Subscriptions 5. Please disable this plugin, either from the back-end of your site or by renaming the xxxx/libraries/cms/plugin folder to helper.php.bak for this message to disappear. After refactoring the code of this plugin for Akeeba Subscriptions 5 you can re-enable it.

>EXTREMELY IMPORTANT: Do NOT ask Akeeba Ltd for support regarding this message. None will be provided and your request will be deleted without a reply. Support for Akeeba Subscriptions was terminated on November 2013. We regret to inform you that due to lack of available time we will not be available for any bespoke projects. We additionally regret to inform you that we cannot recommend a developer for this task.

Basically I have nothing against the message, except that it doesn't tell me which plugin is incompatible??? I'm sure that it isn't xxxx/libraries/cms/plugin/helper.php

**Comment by nikosdion** [comment]
Hello Daniel,

That would be impossible to report since PHP doesn't tell you which file included you unless you throw an Exception and you have an exceptions handler. See how my attempt to report the plugin failed? All you can do is trial and error.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by compojoom** [comment]
As usual - it was the last plugin I thought of... Our payment plugin for sofortüberweisung. Thanks!
