### ISSUE TITLE
IPN changes?

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#160]
Hey Nick,
Since I updated to the latest version from git my site no longer receives the IPN callback. 

The url called that is listed in paypal for callback is: index.php?option=com_akeebasubs&view=Callback&paymentmethod=paypal -> which seems to be the correct URL (when I directly call it in the browser I get FAILED, which is also correct).

I've resend the IPN callback in paypal & the delivery status changed to failed again. The joomla IPN log file is missing any entries for the IPN callbacks since I updated. 

The same happened to the 2checkout plugin - no IPN calls since the update? Do you have any ideas where to look?

**Comment by compojoom** [comment]
I don't know if this helps, but when I resend the IPN message in Paypal I get a notification about the failed delivery. The url in the mail is:
index.php?option=com_akeebasubs&view=callback&paymentmethod=paypal - all lowercase. Where the url in Paypal has Callback uppercase - it doesn't seem to make any difference (don't get a 404), but thought that maybe it will give you a clue?

**Comment by nikosdion** [comment]
When you click on Subscribe Now check what the notify_url attribute of the (auto-submitted) PayPal form reads. It should be something like http://www.example.com/index.php?option=com_akeebasubs&view=Callback&paymentmethod=paypal  If it looks any different something's wrong with your PayPal plugin. Maybe an old version of it? If you are using the packaged 5.0.0.b1 beta version please note that it DOES have a bug. Use the code from the GitHub repository instead.

**Comment by compojoom** [comment]
that is the  notify_url I see in the paymentform index.php?option=com_akeebasubs&view=Callback&paymentmethod=paypal

I've build the package from git from Commits on May 11, 2015 

The version of the plugin is 5.0 from April 2015

**Comment by nikosdion** [comment]
Please clarify: is the URL *exactly* `index.php?option=com_akeebasubs&view=Callback&paymentmethod=paypal` or does it contain the protocol prefix and domain name of your site, e.g. `http://www.example.com/index.php?option=com_akeebasubs&view=Callback&paymentmethod=paypal`

The former is wrong, the latter is correct.

**Comment by compojoom** [comment]
sorry for being unspecific. The url contains domain and protocol prefix:
```
http://www.example.com/index.php?option=com_akeebasubs&view=Callback&paymentmethod=paypal

**Comment by nikosdion** [comment]
I can't reproduce this :(

I created a local test site with a web-accessible URL (thanks to DynDNS) and tested with the PayPal Sandbox. I receive the IPN just fine, it is logged as valid and the subscription gets activated. I tested a regular subscription, not an auto renewing one. I suppose that's the same thing you're doing, right?

One thing to note is that it doesn't matter what IPN callback URL you define in PayPal's configuration. It is overridden anyway, that's why I asked you previously.

Is it possible that your server is rejecting the IPN request coming from PayPal? The IPNs are known to trigger some mod_security2 rules. I remember that 5 years ago I had to ask Rochen to disable some rules to let the PayPal IPNs work. Does that help?

**Comment by nikosdion** [comment]
One more thing. Make sure you're also running the latest FOF 3 code. That's what I tested against. I'm not sure which version of FOF 3 you're using.

**Comment by compojoom** [comment]
F0F3 revDB9F10A-1431678006 - that from the 15th of May. 
I'll ask siteground if they know something, but it is strange because it started failing immediatly after updating to the latest akeebasubs release. Will have to spend some time debugging. 
Will let you know how it goes.

Regards,
Daniel

**Comment by nikosdion** [comment]
Normally the changes I made in FOF 3 between May 15th and 24th should have no effect. I only added features, I didn't change existing ones.

Hm, could this simply be a coincidence? I do remember that PayPal would "forget" to send me IPNs at random intervals and these outages went on for anywhere between half a day to a week. That was the main reason I stopped using them as the primary payment processor, long before moving to 2Checkout.

**Comment by compojoom** [comment]
Maybe it is a coincidence. I just used the paypal sandbox and sent few IPNs to the server. They all went through! Everything was written to the log. Then I logged in my live account in paypal and tried to resend the items and they failed. 

I went again to IPN simulator and send again and I got a 502 message this time. So most probably that's why the messages are not arriving. We'll see what siteground will find out.

Thanks for the help as usual!

**Comment by nikosdion** [comment]
Is your site behind a CDN or a proxy? That would explain the HTTP 502...

**Comment by svenbluege** [comment]
Just to add my IPN experience here: I switched my site to HTTPS and forced this protocol by .htaccess. Paypal does not support SSL on shared host environments and I got this 502 for each IPN. The paypal payment method should have a switch to force the http protocol. Maybe this is helpful for someone.

**Comment by nikosdion** [comment]
There is a switch in the payment plugin to set the callback method to HTTP, HTTPS or default (whatever the site is supposed to be using).

**Comment by compojoom** [comment]
There is a switch, but I don't agree with you Sven. I'm on a shared host for some years now with ssl (https) and never had issues with the IPNs because of this. 

Nick, I'm on siteground. Here is what they told me right now:
>I have once again reviewed all the access logs and error logs for the past few days but to no avail. Would it be possible for you to contact PayPal and kindly ask them to supply any information on this and any IPs for which we can search in our logs and track down the core of the issue which you are experiencing.

>Without any further information it will be nearly impossible to locate the source of this.

**Comment by nikosdion** [comment]
Hm, I guess it means they never saw the request hitting their server? I mean the callback URL is rather unique and nobody else is hitting it, so...

**Comment by tampe125** [comment]
I'll toss my 2 cents in here, too. Do you have Admin Tools installed on your site?
Some time ago I discovered that the CSRF shield was blocking PayPal callbacks.
Most likely this is not your cause, but let's uncheck all possible reasons.

**Comment by compojoom** [comment]
I do have admin tools, but why would it block the IPN messages from time to time & not all the time?

And it is not a paypal problem as 2checkout notifications aren't coming either...
Wrote to paypal, let's see what they will respond :)

Again thanks for the help & suggestions!

**Comment by nikosdion** [comment]
If you're using CSRFShield or XSSShield in Admin Tools then the IPNs *will* get blocked: always with CSRFShield, sometimes with XSSShield. I believe that's what Davide had in mind.

The CSRFShield requires all POST requests to have a token (Basic, Advanced) and not have a known "bad" value (Advanced). Since the IPN will never have a token it will be blocked, but this results in a 403 error, not a 502.

The XSSShield looks at the content of the submitted values and tries to guess when they contain cross-site scripting code. This is not an exact science (if it was XSS attacks would be dead) so it does produce a lot of false positives. Again, if it blocks something it results in a 403 error, not a 502.

Both Admin Tools features in question are designed for simplistic sites, not e-commerce / client support sites like ours. You should disable both of them.

**Comment by compojoom** [comment]
Thanks for the help guys! 
Yes, if it was admintools, then I was supposed to have a response code in paypal live (but I had nothing) and the simulator was returning sometimes 502. 

In case someone else needs it here is the list with the paypal IPs:
https://ppmts.custhelp.com/app/answers/detail/a_id/92/

It turned out that siteground had blocked one of the notification IPs, and that's why paypal was never reaching my site. Now they've removed the rule from the firewall and IPNs are being delivered again! Yahooooooo! 

On a separate note - I've noticed that right now both view=Callback and view=callback are working. Is the lowercase view=callback left because I've updated from a previous version and something was not deleted, or is it supposed to work so???

**Comment by nikosdion** [comment]
The lowercase views are mapped to the new CamelCased views for backwards compatibility. It's a Dispatcher and router.php trick :) The idea is that recurring subscriptions cannot be upgraded without asking the user to manually cancel them and resubscribe which of course is not going to happen. So we're using the internal mapping to make sure we don't screw up these recurring subscriptions. Neat, huh?

**Comment by compojoom** [comment]
Awesome, not neat! :)
