### ISSUE TITLE
When accessing Subscription the ordering is wrong

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#161]
When you login for first time to the backend and navigate to the subscriptions, the id column is shown as DESC, but the list with subs is actually in ASC order.
If you click twice on the id it will be reordered.

I check the generated query in onAfterBuildQuery

```
SELECT *
FROM vpo_akeebasubs_subscriptions
ORDER BY `akeebasubs_subscription_id` ASC

In the dataModel we have this

```
$dir = strtoupper($this->getState('filter_order_Dir', 'ASC', 'cmd'));

		if(!in_array($dir, array('ASC', 'DESC')))
		{
			$dir = 'ASC';
		}

So obviously the default value when not set in the state is ASC. Where should I put the state? The subscription model doesn't have a populate state function. What's the right way to do this in F0F?

**Comment by nikosdion** [comment]
The display issue comes from a bug in FOF 3. I just fixed it.

As for the default ordering of subscriptions and invoices, I just pushed a change to Akeeba Subs' repo.
