### ISSUE TITLE
Filter for created on?

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#162]
Hey Nick,
Am I misunderstanding something or the filter for created on is not properly working on the subscriptions page?
No matter what date I select, I don't see the subscriptions created on that date???

**Comment by nikosdion** [comment]
The operator is greater than and the date expressed in GMT. Makes sense?

**Comment by compojoom** [comment]
Aaaaah. Okay. Okay. I understand this now. 

Isn't from till more appropriate? from 00:00 till 23:59:59 ?

**Comment by nikosdion** [comment]
From/to would be best, but the form looked like crap. It's already too loaded with fields. Besides, most of the time you want to search for values in the future.

**Comment by compojoom** [comment]
No I meant - keeping the same field that we have now for entering a date. And then the query just searches for all sales on that particular day. 
"Created on" means created on that day and not "on that day + the future". If we want to keep the same behavior then I would rename created on to created since. This way it won't be that confusing for my little brain :)

**Comment by nikosdion** [comment]
Ah, I see. Well, honestly? Because I usually search "from that date onwards". Also because I'm lazy: changing the filter requires 5 lines of code :p Joking aside, if you sort by Valid From ascending and use the filter as it is now you can get the result you want very easily.
