### ISSUE TITLE
1064 You have an error in your SQL syntax

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#165]
There is an error in the sql query on the subscription page when we search for a user that is actually not in the database. (let's say we have a typo in the username)

>1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) OR (`businessname` LIKE '%fdsafasfsafasf%') OR (`vatnumber` LIKE '%fdsafasfsa' at line 6 SQL=SELECT * FROM #__akeebasubs_subscriptions WHERE (( SELECT COUNT(*) FROM `#__akeebasubs_users` AS `reltbl` WHERE `reltbl`.`user_id` = `#__akeebasubs_subscriptions`.`user_id` AND ((`user_id` IN ()) OR (`businessname` LIKE '%fdsafasfsafasf%') OR (`vatnumber` LIKE '%fdsafasfsafasf%'))) >= '1') ORDER BY `akeebasubs_subscription_id` DESC LIMIT 0, 20 

It would be way better to just show "no subscription found" or even better "that user doesn't exist you moron" :D

**Comment by nikosdion** [comment]
I don't understand. The subscription page (front-end, view=Subscribe) creates the user if the user doesn't exist. Which view are you talking about and exactly what did you try doing? Also, which version of FOF 3 do you have installed?

**Comment by nikosdion** [comment]
Ah, I see what you mean! The back-end Subscriptions view. OK, I'm on this.
