### ISSUE TITLE
Valid date wrong when user has a different subscription

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#166]
Hey Nick,
I had few users now that complained about a wrong valid from date when they subscribe. 

What seems to happen is: 
1. The user has subscription that expires in 2016
2. The user decides to buy a different subscription (not sub. relation whatsoever) and the valid from date is set to the expire date of the previous subscription. 

Have you experienced this?

**Comment by nikosdion** [comment]
If you put subscriptions in the same group OR if you create a subscription relation of the "Extend" type (instead of Overlap or Replace) then yes, this is what will happen. Is this the case?

**Comment by compojoom** [comment]
I checked those already yesterday and that was not the case. Will check again and will let you know.

**Comment by compojoom** [comment]
![sub-rel](https://cloud.githubusercontent.com/assets/693770/8234208/d01c15d6-15da-11e5-9c24-1ade4d1e5ee2.PNG)
Here is the sub relation. 
The user had a Matukio sub. Later the same day he subscribed for Hotspot. And the Hotspot valid from ended being the end date of the Matukio sub.
Do you see any way for this to happen by the sub relation in the screenshot? To me it seems all correct.

**Comment by nikosdion** [comment]
Is there any pattern among those affected users? For example, do they have any payment problems? The actual Valid From date is applied by AkpaymentBase::fixSubscriptionDates. This method is unit tested in https://github.com/akeeba/akeebasubs/blob/development/Tests/Admin/PluginAbstracts/AkpaymentBaseFixDatesTest.php

**Comment by compojoom** [comment]
If there is a pattern I'm failing to see it right now. 
Yesterday another guy wanted to renew his Matukio subscription. 
On his account he also had a 3 year subscription for Hotspots. 
By renewing his Matukio subscription the valid date for the Matukio sub was set to 3 years in the future. 

So I thought that I had configured a wrong sub. relation. But that was not the case.

**Comment by nikosdion** [comment]
Was his Hotspots subscription in the same *Subscription Level Group* as the Matukio subscription he bought? Remember, Level Groups do exactly what you describe. If you have groups you need to *remove* the subscriptions from the groups.

**Comment by compojoom** [comment]
I have level groups, but each subscription level is in the correct level group.
All matukio levels are in the Matukio level group. and all Hotspots levels are in the Hotspots level group.

**Comment by compojoom** [comment]
Can I somehow manually trigger the fixSubscriptionDates function? I could create a similar situation for my user and see if anything wrong happens.

**Comment by nikosdion** [comment]
See the Unit Tests. It's a static method so yes, you can call it anytime.

**Comment by compojoom** [comment]
I found the issue and it is in the subscribe model. 
You are passing an array to the akeebasubs_level_id magic function, but you should be using just level there.

Can you explain something to me though. When I was debugging instead of passing an array to the akeebasubs_lebel_id I tried passing an integer. And I actually always got any subscription the user had. No matter what integer I pass to the function??? Any idea why this is happening and why the query was not restricted by level?
