### ISSUE TITLE
Graphs on the dashboard are not actually showing the correct data???

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#171]
Surprise, surprise! It's me again :D
It's been some time now that I've been wondering at the dashboard and why it no longer shows the correct information. Am I the only one again with this problem?
![graphs](https://cloud.githubusercontent.com/assets/693770/8376111/322dcb98-1c0c-11e5-8445-8fcc2c4f1d68.PNG)

For me the generated graphs only show a single day and a single level. Not all levels as before and not the last 30 days?

**Comment by nikosdion** [comment]
Hm, are you running the latest Git development branch of FOF 3 or the very old one shipped with AS 5.0.0.alpha1?

**Comment by compojoom** [comment]
fof3 version rev81B1BB7-1435313068 (just build AS with the latest code from today)

**Comment by nikosdion** [comment]
Check out the latest development branch of both FOF 3 and Akeeba Subs. It should now work properly.

**Comment by compojoom** [comment]
Thank you! It works as expected now!

**Comment by nikosdion** [comment]
Awesome! Thank you for the bug report :)
