### ISSUE TITLE
Invoice DLID

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#172]
In my invoice I had a replacement value [DLID] which was previously being replaced by the download id from ARS. This no longer is being replaced. Is this tag still valid?

**Comment by nikosdion** [comment]
It should be. Which version of ARS are you using?

**Comment by compojoom** [comment]
Akeeba Release System 2.5.1

**Comment by nikosdion** [comment]
Can you try with ARS 3? IIRC I changed the code to work with ARS 3.
