### ISSUE TITLE
You need Joomla! 3.4.0 or later to install this component

### ISSUE THREAD

**Issue by huba80** [akeeba/akeebasubs#181]
I just love this component and I thought it is time to upgrade it from 4.1.1 to 5.0.
My Joomla is 3.3.6 and I tried to upgrade it via Joomla Extension manager. Unfortunately I couldn't.
I get a warning: "You need Joomla! 3.4.0 or later to install this component"

"JLIB_INSTALLER_ABORT_PACKAGE_INSTALL_CUSTOM_INSTALL_FAILURE"

I read the release notes and I didn't find anything regrading Joomla version limitation. Only this:
"API changes found only in Joomla! 2.5.6 or later, this version will not install on Joomla! 2.5.5 or earlier versions. In any case, it will tell you exactly why it cannot be installed"

I'm not quite sure if this is how it supposed to be or a bug. I just thought I let you know. 

Thanks

**Comment by nikosdion** [comment]
Not a bug at all. You should upgrade to Joomla! 3.4. There's no reason to stay with the obsolete and insecure Joomla! 3.3.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by huba80** [comment]
I wanted to upgrade your component before I upgrade to J3.4 to avoid problems after Joomla upgrade. Unfortunately there is no compatibility notes at 5.0 download page. There is no comment on the download page that this 5.0 version is not J3.3 compatible.

Other warning at upgrade:

"JLIB_INSTALLER_ABORT_PACKAGE_INSTALL_CUSTOM_INSTALL_FAILURE"

**Comment by nikosdion** [comment]
That one is thrown by Joomla! itself when the package declines the installation.

You will not have a problem if you upgrade to Joomla! 3.4 first and upgrade the component later.

As for release notes, do remember that these releases do come with no support. All notes are for internal reference only :)

**Comment by huba80** [comment]
Im 100% aware of that there is no support. I didn't know if this is bug or not. All Akeeba Subscriptions versions have compatibility notes and they are compatible with even J3.2. They have compatibility notes even after when you cut the support of this component. For me it was't obvious that this 5.0 is not compatible with J3.3. I just thought I report it maybe it is bug. I though it may help and I didn't open this thread to complain about lack of support.
With 90% of Joomla extensions you can't just upgrade Joomla to a higher version because not every extension is ready for higher Joomla version. Upgrading Joomla to a higher version before checking all installed extensions compatibility may result a blank page and takes twice as much effort to find out why. It is better safe than sorry to check and upgrade the extensions first and upgrade the Joomla at last.

Thanks for answering.

**Comment by nikosdion** [comment]
OK, makes sense :) Sorry for misunderstanding you.
> With 90% of Joomla extensions you can't just upgrade Joomla to a higher version because not every extension is ready for higher Joomla version. Upgrading Joomla to a higher version before checking all installed extensions compatibility may result a blank page and takes twice as much effort to find out why. It is better safe than sorry to check and upgrade the extensions first and upgrade the Joomla at last.
> 
I always try the last release of my software compatible with Joomla! X.Y to also be compatible with Joomla! X.(Y+1). That gives you about 3 months to update your site. Now here's the thing. If there's a new Joomla! X.(Y+2) available you will be left with no upgrade path UNLESS you find an unofficial way to upgrade to Joomla! X.(Y+1) first.
