### ISSUE TITLE
Bug when saving a subscription level

### ISSUE THREAD

**Issue by wilsonge** [akeeba/akeebasubs#189]
![image](https://cloud.githubusercontent.com/assets/1986000/9760807/400bde66-56f0-11e5-9ebe-322db62c199d.png)

I guess this has been fixed - but there's a small bug when you save the subscription level where the top menu and Joomla Notification interfere with each other (maybe an FOF bug? - not sure how your rendering the top bar)

**Comment by nikosdion** [comment]
This is actually bad CSS in Joomla! to render the collapsible sidebar. The navbar I generate uses the standard Bootstrap CSS code. The Joomla! CSS bug goes unnoticed because Joomla! doesn't use a navbar anywhere.

**Comment by wilsonge** [comment]
Something bad in Joomla :O HERESY!!! :P
