### ISSUE TITLE
Datebase warning after installation and missing e-mail templates

### ISSUE THREAD

**Issue by peri0603** [akeeba/akeebasubs#192]
Hi! I have done a akeeba subscriptions 5.0.0 install on a fresh installed joomla 3.4.4.

I get the following messages at the end of the installation:

##begin
Warning

Table 'fvkl4_akeeba_common' already exists SQL=CREATE TABLE `fvkl4_akeeba_common` ( `key` varchar(255) NOT NULL, `value` longtext NOT NULL, PRIMARY KEY (`key`) ) DEFAULT COLLATE utf8_general_ci CHARSET=utf8;

Message

Installation of the package was successful.
##end

![bildschirmfoto vom 2015-09-18 20 05 35](https://cloud.githubusercontent.com/assets/10977991/9967230/96db9134-5e41-11e5-9041-282432eb9de5.png)

I have also checked the e-mail templates and they are all missing/empty.

My system:

![bildschirmfoto vom 2015-09-18 20 13 43](https://cloud.githubusercontent.com/assets/10977991/9967262/cf4ab5b8-5e41-11e5-8352-968e790d0241.png)

Thanks in advance!

**Comment by tampe125** [comment]
Thank you very much for your report!
Regarding the database warning, it was a nasty one, caused by caching the table list.
For what concerns the email templates, I have an hunch on what's going on, I'll try to fix it later during these days

**Comment by peri0603** [comment]
I have now tried the installation of the v5.0.1 of akeebasubs with joomla 3.4.5 and joomla 3.5 beta 1 and everything works well. The installation has no warnings and the standard e-mail templates are available.

Thank you very much for your exellent work and happy bug-fixing
