### ISSUE TITLE
misstype "onle_once"

### ISSUE THREAD

**Issue by gruz** [akeeba/akeebasubs#207]
In 
 akeebasubs/component/backend/View/Levels/tmpl/form.form.xml
You have:
        <field
            name="onle_once"
            type="BooleanToggle"
            label="COM_AKEEBASUBS_LEVELS_FIELD_ONLY_ONCE"
        />

name should be "only_once"

**Comment by nikosdion** [comment]
Closed with https://github.com/akeeba/akeebasubs/commit/9dc03050d36a98ee978f56ac23686ec72fe0c81b   Thank you for your bug report!
