### ISSUE TITLE
Akeeba Subscriptions module - "List subscription levels" gives a fatal error when trying to subscribe

### ISSUE THREAD

**Issue by gruz** [akeeba/akeebasubs#213]
Latest development branch rev80C045E

When the module is published and I try to subscribe and press the button I'm redirected to a link like
index.php?option=com_akeebasubs&view=Subscribe&layout=default&slug=hikashop-canadapostary-6-month&Itemid=560

And get an error:
Fatal error: Cannot use Akeeba\Subscriptions\Site\Model\Subscribe as Subscribe because the name is already in use in /mnt/sda2/work/www/arygroup.ga/www/components/com_akeebasubs/Controller/Levels.php on line 13

When the module is unpublished or published excluding AkeebaSubs pages, then I don't get the error.

It's worth of notice, that the problem appears to a non-free subscription plan. For a free one - it works.

=======================================================
Besides there is another problem, which is rather strange and also tied to the module.

On some circumstances when I register to a free plan and the user need to activate a emails, it's immediately logined (though it's not activated). 
Look what I mean in screenshots:
Here I subscribe
http://view.xscreenshot.com/3298f5d8a2caf77fb3a1d8aae75a2335
And after I press the button I get a logged in non-activated user, and a 404 page
http://view.xscreenshot.com/cb5cd9a35f11b0f333a8522600dbc433

This behaviour I meet when the module is published with the only free plan in it.
http://view.xscreenshot.com/c6c116828f943426913ce16a66d049dc
If I show all plans in the module, then it works
http://view.xscreenshot.com/4e161d5465d78dc0cf5ca847a653e019

Well, I don't badly need the module, I can avoid using it. Just want to inform you that there is a problem. It took me a couple of days to find out, that it was the module to create me the problems.

Thank you.

**Comment by nikosdion** [comment]
This is actually an older dev release. Can you please try the new dev release of Akeeba Subscriptions I have uploaded to http://akeebabackup.com/download/developer-releases/akeebasubs-dev It's 
rev913CA00.

**Comment by gruz** [comment]
Akeeba Subscriptions rev913CA00

The module enabled with all subscription.  After press subscribe button.

A paid subscription. 
Link: index.php?option=com_akeebasubs&view=Subscribe&layout=default&slug=hikashop-canadapostary-1-month
Fatal error: Cannot use Akeeba\Subscriptions\Site\Model\Subscribe as Subscribe because the name is already in use in /mnt/sda2/work/www/arygroup.ga/www/components/com_akeebasubs/Controller/Levels.php on line 13

A free subscription: works.

=================

The module enabled with the only free subscription.  After press subscribe button.

The free subscription
Link: index.php?option=com_akeebasubs&layout=order&view=message&slug=one-day-subscription&subid=30
Result: a logged in non-activated user
Screenshot: http://view.xscreenshot.com/f179bafa5697fdf0588f8448fa6fb006

A paid subscription.
Fatal error: Cannot use Akeeba\Subscriptions\Site\Model\Subscribe as Subscribe because the name is already in use in /mnt/sda2/work/www/arygroup.ga/www/components/com_akeebasubs/Controller/Levels.php on line 13

So nothing changed with the issues in the latest update.

If you are eager to solve the issue, maybe I should provide you my web-site akeebabackup so you can examine the problem on live data. 

Thank you.

**Comment by nikosdion** [comment]
The latest commit should fix that. You can replace your components/com_akeebasubs/Controller/Levels.php with the component/frontend/Controller/Levels.php from this repository.

**Comment by gruz** [comment]
Installed rev4861FBB

Now the module doesn't allow to show all subscription levels.
Though no level is selected in the module settings
http://view.xscreenshot.com/b7580baa492241c6eb9b012174587c47
It shows the last one which was selected before. So I have to show which levels to show manuall, not possible to select "all" or "none" which should mean all.

So I selected several subs.levels to be shown in the modules and here are my try results:
A paid subscription - on subscribe 
Link is /index.php?option=com_akeebasubs&view=Message&slug=hikashop-canadapostary-1-month&layout=order&subid=32
And I get a 404 error
http://view.xscreenshot.com/0ac2a5539a135cbee632286a6001c2fa
The user is logged in, but as it's a paid plan it's en expected behaviour.
I tried to relogin and still get the same message at the same page
Just in case, Plugin System - Akeeba Subscriptions Logout user is enabled. 

The same happens for a free subs. sign up. But the free user shouldn't be logged in as it's not activated.

===========

Unpublished the module.
A paid subscription redirect and logins work ok.
A free subscription - now I meet the non-activated user logged in and the 404 error. 


So it seems that comparing to my initial problem, the fatal error is solved, but strange login isn't solved and the problem added to the "no-module free subscriptiion" situation.

**Comment by gruz** [comment]
A kind of block-scheme to show the test results and problems.

<a href="http://view.xscreenshot.com/136d09f790671a0b87118809e70b1396" rel="group[xscreenshot]"  class="jcepopup"><img width="300" src="http://static.xscreenshot.com/2015/10/22/14/screen_136d09f790671a0b87118809e70b1396"></a>

**Comment by gruz** [comment]
Please, disregard my previous message. I test now in several hours and get other results. Maybe something was tied to session stored in the DB. I'll let you know when I get more clear test results.
