### ISSUE TITLE
Saving subscription in admin panel removes existing params

### ISSUE THREAD

**Issue by piotrmocko** [akeeba/akeebasubs#218]
After saving a subscription in the admin panel 
all existing params created during payment process, eg. {"fixdates":"oldsub":null,"allsubs":null,"expiration":"overlap"}
are being replaced with {"subcustom":[]}

This replacement is made in method AkeebasubsControllerSubscriptions::onBeforeApplySave
Currently I do not have a simple solution to fix it 
and I have commented it out as I do not use subcustom.

Branch 4.x
Method AkeebasubsControllerSubscriptions::onBeforeApplySave
https://github.com/akeeba/akeebasubs/blob/4.x/component/backend/controllers/subscriptions.php

**Comment by piotrmocko** [comment]
and I do not know why in
https://github.com/akeeba/akeebasubs/blob/4.x/component/backend/views/subscription/tmpl/form.php
$this->item->params
are replaced with
$this->item->params['subcustom']
on line 31

**Comment by nikosdion** [comment]
Is this linked to your other PRs today or should I take a look at it?

**Comment by piotrmocko** [comment]
This is not related to my today's PRs, you can take a look at it

---
Pozdrawiam
Piotr Moćko
3 lis 2015 15:21 "Nicholas K. Dionysopoulos" <notifications@github.com>
napisał(a):

**Comment by nikosdion** [comment]
This is fixed in Akeeba Subscriptions 5. The only way to properly fix it is using the FOF 3 framework which handles parameters fields much more gracefully than FOF 2. Sorry, it's unfixable in AS 4 :(
