### ISSUE TITLE
"Export to CSV" Function Not Pulling Name, Address, Phone or Custom Data

### ISSUE THREAD

**Issue by bryanearl** [akeeba/akeebasubs#227]
The "Export to CSV" function (in Subscriptions) does not pull the users name, address, city, state, zip or any of the "Custom Field" data.

Not sure if this is a bug or if it was intended that way...  However, that information is typically vital to a CSV export.

**Comment by nikosdion** [comment]
We can't pull in the extra fields in the CSV export (it gets very messy very fast) but at least I can export some basic user information.

**Comment by bryanearl** [comment]
I made the changes and it looks much better, but it appears that there are two database fields that are fighting and not displaying correctly...

 

The payment "state" and the location "state".

**Comment by bryanearl** [comment]
In the previous version, all of the custom field data was exported along with the rest, it was just all in a single field, separated by commas.  it was messy, but at least it was there.

 

Is this possible?

 

Thank You

**Comment by nikosdion** [comment]
No.
