### ISSUE TITLE
Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given

### ISSUE THREAD

**Issue by RickR2H** [akeeba/akeebasubs#229]
After installing version 5.0.1 I get an error on register as a new customer.

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, boolean given in /home/deb3757n305/domains/inquiries4engineers.com/public_html/libraries/joomla/database/driver/mysqli.php on line 343
![image2](https://cloud.githubusercontent.com/assets/5610413/11298678/19878e88-8f81-11e5-9f31-94bdf4a99907.jpg)

**Comment by nikosdion** [comment]
I can't reproduce this locally. Moreover, this is a PHP warning coming from Joomla!'s database driver.
