### ISSUE TITLE
Subscriber emails not sending

### ISSUE THREAD

**Issue by edinmark** [akeeba/akeebasubs#232]
Just a bug report from my recent experience with Akeeba subs:

this regards Subscriber emails. 

Subscriber emails plugin is published, yet no subscriber emails are sent on change of subscription status (activate, expired, etc.). Debug is off, obviously, and SMTP is set up with other emails sending fine.

Admin emails and expiry notification emails send without problem. 

I note that in the email customise template configuration drop-down box "admin emails" and "notification emails" are available for template configuration, but there are no "subscriber emails" available to configure, suggesting the program is not recognising the Subscriber email plug in. 

My set-up: Joomla 3.4.5
Akeeba subs: 5.0.0

**Comment by nikosdion** [comment]
Publish the "Akeeba Subscriptions - Emails" plugin. It seems that you don't have it published.

Akeeba Subscriptions, Setup, Email Templates. You need a template under Subscriber, e.g. Miscellaneous subscription change. Language must be set to "(All)" (unless you have a template per language, read the docs), subscription level must be empty (unless you have a template per level, read the docs) and Enabled must be checked (green check).

NOTE: Different templates are used for different status changes. Read the names of the template types, they are very descriptive.

I have tested just now using the latest dev release (equivalent to 5.0.1 plus minor, unrelated bug fixes), Joomla! 3.4.5, all emails are sent correctly.

**Comment by edinmark** [comment]
Thanks very much for your response Nikos, 

I really appreciate it. 

The behaviour persists on my side, unfortunately. 

The plugin "Akeeba Subscriptions - Emails" is definitely published. 

However, while admin emails and expiry notifications are sent (by separate plugins, of course), Subscriber "change in subscription status" emails are not sending. 

Its as though the "Akeeba Subscriptions - Email" plugin is unpublished, but it is definitely published!

When I go to Setup >> "email templates", there are options for me to configure templates for:

- "Administrator" emails
- "Expiration Notification" emails
- "Integrated Invoicing" emails

But there is no option to configure Subscriber emails.  See the screenshot attached: in the dropdown box there are no Subscriber emails as a choice to configure.  This leads me to believe the plugin is behaving as though it is unpublished, even though it is published....

![screen shot 2015-12-13 at 15 12 13](https://cloud.githubusercontent.com/assets/16230593/11767700/ffecb190-a1ac-11e5-84da-c9d0e38c32e6.png)

![screen shot 2015-12-13 at 15 10 03](https://cloud.githubusercontent.com/assets/16230593/11767713/639f3df2-a1ad-11e5-90e3-75d38de20aa2.png)



kind regards,
Mark

**Comment by edinmark** [comment]
Just a further update on testing:

I have installed Akeeba Subs 5.0.1 package from Akeeba website on a fresh Joomla! 3.4.5

Again, the plugin "Akeeba Subscriptions - Emails" is published. 

Again, a new subscription sends Admins an email notification (different plug-in, of course) but Subscribers do not receive notification of an activated/changed subscription.

On the Setup >> Email Templates page, I note that there are 12 default "subscriber emails" templates which appear to be included as part of the package install.  (See screenshot)

Interestingly, they are labelled as 'Email Type':  "Expiration Notification - First" 

rather than being labelled as "Subscriber email" (or similar expected label title)

Again, in the drop-down menu for email templates the options are:

-  "Administrator" emails
-   "Expiration Notification" emails
-  "Integrated Invoicing" emails

but there is no option for "Subscriber emails"

All of this behaviour suggests to me that in the latest Akeeba Subs Package installs, the plugin for "Akeeb Subscriptions - email" is misbehaving and not being appropriately activated despite being published.

![screen shot 2015-12-13 at 16 22 49](https://cloud.githubusercontent.com/assets/16230593/11768009/6b8d042c-a1b7-11e5-936f-a23b3dc7a2f8.png)

**Comment by nikosdion** [comment]
I only see a part of the drop-down. Subscriber emails would appear much further down the list.

**Comment by edinmark** [comment]
they don't though. 

all the rest of the drop down is attached below:

![screen shot 2015-12-13 at 18 12 55](https://cloud.githubusercontent.com/assets/16230593/11768451/3daa1f5a-a1c5-11e5-8699-9c65c875a7d4.png)

**Comment by nikosdion** [comment]
Maybe try upgrading Akeeba Subscriptions? There were a lot of bug fixes in 5.0.1.

**Comment by edinmark** [comment]
I tried Akeeba Subs 5.0.1 but the same behaviour as outlined above.  

I also tried with a clean install of Joomla! 3.4.5 with Protostar default template and no other plugins or extensions downloaded outside of Joomla core. 

...still no subscriber emails.   

must be a bug hidden somewhere

**Comment by nikosdion** [comment]
Same software both on my local servers (Mac, Linux and Windows) and our live site do send out emails just fine.

Just to be clear, I am doing two tests: change the expiration date by one day (miscellaneous subscription change) and changing the expiration date to the past (subscription becomes inactive).

Please note that some changes are not meant to send out emails, e.g. when you change the payment information (payment method, payment key, prices), the IP address / country of the subscriber, slave subscriptions, custom fields, subscription level etc. The data change that triggers an email is limited to valid from/to date, published and payment state. Maybe you have the wrong expectation of which emails should be sent out?

Furthermore you can directly compare the admin emails and the regular emails plugins. You'll see they're identical except the target email address. You can't really have a "bug" in one but not the other in the way you describe that.

**Comment by edinmark** [comment]
Hi Nikos, 

As always, thanks for your help and looking into it.  I really appreciate it.  I still suspect something is wrong with Akeeba Subs 5.0.x. here.  

I am running a clean install of Joomla! 3.4.5 with Akeeba subscriptions 5.0.1 package via Akeeba's website.

Akeeba Subs "Admin email" and "subscriber email" plugins are both published.

Action => Result
I create a new subscription => Admin gets an email; No subscriber email
I change the expiry date by 1 day ==> Admin gets an email; No subscriber email
I change date to expire subscription ==> Admin gets an email; no subscriber email

If I go to Set-up >> Email templates,  Admin emails are available as a type of email to edit, but no subscriber emails are seen in the dropdown (as I described earlier).  The subscriber plugin is clearly not being recognised. 

<b>Now, look at this interesting behaviour I've just discovered: </b>

If i turn off Admin emails plugin, but leave subscription email plugin on, lo and behold, in Setup >> Email templates, Subscriber emails automagically appear as an option to edit (see screenshot). Of course, admin emails don't because the plugin was turned off.  When i test activating new subscriptions, I also start getting subscriber emails when subscription status changes occur!

![screen shot 2015-12-15 at 21 50 11](https://cloud.githubusercontent.com/assets/16230593/11825448/efe17d8c-a376-11e5-8b91-6ac2446f4691.png). 

So the Admin Email plugin, when it is turned on, is interfering with the function of the subscriber email plugin.  When admin email plugin is off, subscriber emails work fine!

With your recent tests, have you downloaded the package as it exists on your Akeeba website or are you using a locally stored version of the software? Perhaps the two are different.  I would be curious to see what result you get with a clean install of Joomla and a new install of the package 5.0.1, as it exists on the website. 

bw,
Mark

**Comment by edinmark** [comment]
Nikos, 

Problem solved!  Or rather, problem circumvented!

With the package 5.0.1 install, the default plugin order is for admin emails to appear before subscriber emails in the plugin order (ID 10009 vs ID 10026 in my install). 

I have reversed the order so that Subscriber email plugin occurs before Admin email plugin: Bingo!
(This is probably the order you have in your setup)

Both admin and subscriber emails are sent and both appear in the template as "editable"  types of emails!    yay. 

I don't believe this is expected behaviour.. or at least i couldnt find it in docs; but glad the issue can be solved by a switch of plugin order.
