### ISSUE TITLE
Edit User profile view looks for the 'agree to terms' filed too

### ISSUE THREAD

**Issue by sasivarnakumar** [akeeba/akeebasubs#235]
Edit user profile also validates below plugin fields,
Akeeba Subscriptions - Agree to EU terms
Akeeba Subscriptions - Agree to Terms of Service

Edit user profile uses the subscribe model isValid function and in turn it validates and looks for the above terms checkboxes. It should be ignored.

**Comment by nikosdion** [comment]
Behavior by design. See the code to understand why.
