### ISSUE TITLE
Sales per level graph displays double data series

### ISSUE THREAD

**Issue by nikosdion** [akeeba/akeebasubs#239]
See this screenshot https://www.dropbox.com/s/q5scw04dehoi5b8/Screenshot%202015-12-27%2021.38.18.png?dl=0

This happens only when the date range spans two or more months, e.g. November 27 to December 27. Each subscription level gets a new data series for each month there's data for it. There should be ONE data series for ALL months.

**Comment by tampe125** [comment]
Closed as user error
