### ISSUE TITLE
All of my subscriptions no longer displays expired subs

### ISSUE THREAD

**Issue by royhaanen** [akeeba/akeebasubs#244]
I am using version 5.0.2 of Akeebasubs. Using the menu item "All of my subscriptions" only the active and pending subscriptions are displayed. The expired ones are missing. I know that in 5.0.0 the expired ones also were displayed. What has happened?

Thanks,
Roy

**Comment by nikosdion** [comment]
Cannot reproduce.

Please make sure that if you had done any template overrides they are updated.
