### ISSUE TITLE
Expiration email sent 3 times

### ISSUE THREAD

**Issue by royhaanen** [akeeba/akeebasubs#245]
Hi Nicholas,

I have enabled the System - Akeeba Subscriptions Expiration Notification plugin and set up the levels to send expirations. I am using a cron job on Siteground that is triggered once a day to check for expired accounts. The email are sent fine, but they are sent 3 times in stead of once...

Do you know what is going on? Is this a misconfiguration or a bug? 

Thanks,
Roy

**Comment by nikosdion** [comment]
This is a side effect of using a system plugin to perform a time intensive operation. If a request comes in before emails are sent you have multiple processes sending out those emails.

You can use the akeebasubs-expiration-notify.php CLI script in a regular CRON job to send out these emails instead.

**Comment by royhaanen** [comment]
Ok, so I disable the system plugin and run the script in a CRON job.

I will try it, thank you!

**Comment by royhaanen** [comment]
Nicholas,

If I disable the System - Akeeba Subscriptions Expiration Notification plugin and run the CLI script (which is active right now), will the customers receive the custom email I have set up or receive the default email for expiration notification? 

If I disable the plugin the custom email still shows in the backend as active but the type has become "Subscriber - A pending subscription just got paid", which makes sense but will it still be sent or not?

Thanks,
Roy

**Comment by nikosdion** [comment]
The email template is set component-wide. It doesn't matter how you trigger the email code.

> If I disable the plugin the custom email still shows in the backend as active but the type has become "Subscriber - A pending subscription just got paid", which makes sense but will it still be sent or not?

It will be sent. However, you can do something much easier. Have the CRON job run _before_ the plugin and *two days later* (not today! the CRON job must run at least twice) re-enable the plugin. Therefore you will see the correct labels and no longer be sending multiple emails.

**Comment by royhaanen** [comment]
Check, thanks for the hint! :-)
