### ISSUE TITLE
VAT  number on invoice

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#247]
I got a mail from a user today complaining that my generated invoice doesn't display the full VAT number. It only shows the Numbers, but not the country in front. For example for germany the VAT would be:
DE11111111
but on the PDF we only have
11111111

Am I supposed to put the user's country in front of the VATnumber in the invoice template, or is akeeba supposed to generate a correct VAT number?

When I navigate to the user's view I can see that the VAT number is displayed with the country e.g. DE1111111

Is this a bug or desired behavior for some reason?

**Comment by compojoom** [comment]
I installed this version, regenerated the invoice, but I still see the same result. The invoice has only 111111 as vat number?

**Comment by nikosdion** [comment]
As long as the user selected Business Registration -> Yes and set the country correctly to Germany you should see the correct VAT number in the invoice being generated. I just checked.

**Comment by compojoom** [comment]
The user has Business Registration set to Yes, The country is set to Germany and he has provided a VAT number. 

VAT is VIES registered shows: "No, check again next time", but this shouldn't matter for the display of VAT on the invoice. 

I had a new purchase right now and I can see on it that we have the correct VAT number on the invoice. (the user has the same settings as the other one). But for the old invoice I cannot get it to generate the correct VAT. 

OKAAAAAY! I think that I know what's going on. The regenerate button is sending the correct subscription id, but the generate function in the Invoice controller is fetching the wrong subscription (in my case the latest). 

The model seems to be correct, but $model->subscription is not. I guess that we are loading the wrong relation.Ideas?


Btw, how about changing the form.default.xml for user to:
```
		<field name="user_id" name_from="subscription.user_id" type="User"
			avatar_size="48"
			show_link="true"
			link_url="index.php?option=com_akeebasubs&amp;view=User&amp;task=edit&amp;user_id=[USER:ID]"
		/>
```

This way we could directly go to edit form for the user on the invoices view.

**Comment by nikosdion** [comment]
Thank you for the suggestion and sorry for taking this long. Man, it was a busy week :s
