### ISSUE TITLE
Wrong Price Calculation (Content Price Plugin)

### ISSUE THREAD

**Issue by tassosm** [akeeba/akeebasubs#251]
AkeebaSubs version:  5.0.4
Joomla: 3.4.8
PHP: 5.5.9
MySQL: 5.5.46 
Cache: Disabled

Hi Nicholas,

I'm wondering if someone else is experiencing issues with wrong price calculation including upgrade rules.

It seems that the Content Price plugin returns different results on different pages. On the homepage, it returns a price with no discounts but on an article or on a category page it returns the correct price with the discount rules applied as it's supposed to.

How to reproduce:

1. Create a clean Joomla installation with dummy content
2. Create a new subscription level (Let's name it SUB) with price 10€
3. Create a new upgrade rule for this level (SUB to SUB) with 1€ discount
4. Assign SUB to a test user
5. Create a new Custom HTML module in order to display the price of that level using the Akeeba Subscriptions Price Plugin: {asprice 1}
6. Login to the front-end with the test user

On the homepage, the module shows 10€ as the level price. But, if you visit an article page (with id 1) the module shows 9€.

Is this a misconfiguration or a bug?

Thanks,
Tassos

**Comment by nikosdion** [comment]
The plugin calls Akeeba\Subscriptions\Site\View\Levels\Html's applyViewConfiguration() and getLevelPriceInformation() methods. In their turn they call the validator to return the price. The validator is fully Unit Tested and I've covered even some edge cases you didn't know existed.

Regarding your steps to reproduce, I did that on my dev site and the price is shown correctly both on an article and a module. Caching does interfere with the correct display if the price but this is to be expected. Other than that it's impossible to reproduce this issue. Please double check that BOTH Joomla! AND browser side caching are disabled.

**Comment by tassosm** [comment]
Thank you for the prompt reply.

I don't doubt that the validator is fully Unit Tested and that you've covered a lot of cases already. You've done a great job indeed but I am trying to figure out this strange issue.

I've double checked both Joomla and browser side caching are disabled.

Ι would appreciate if you could take a final look here:

I've uploaded a clean installation of Joomla 3.4.8 with the last version of Akeeba Subscriptions here: http://demo.tassos.gr/test/ 

There is a subscription "Level 1" that costs 10€. There is an upgrade rule (Level 1 to Level 1) with 1€ discount.

On the sidebar, there is module showing the price of Level 1.

Browsing as a guest the price is 10€ οn all pages correctly. 

However, browsing as a subscriber (Log in as manager/manager) the module reports 10€ on the homepage and 9€ on the "About" page. 

If you visit the "Subscriptions" page the Level 1 reports 10€ but if you click the "Subscribe Now" button then the checkout page reports 9€ as the final price.

Is that normal? 
Shouldn't be 9€ on all pages?

Thank you for your time.

**Comment by nikosdion** [comment]
Something is odd with your site, man. The problem occurs only on the home page. Even more weird, if I click on Home and then Subscribe I get the wrong price. Click on Subscribe right after and the entire price summary is missing, as if the Options it reads are from another site. I can't reproduce this anywhere else other than your site. Something something something server related?

**Comment by nikosdion** [comment]
That was tricky...

**Comment by tassosm** [comment]
That was very tricky!  Works perfect.

Thank you
