### ISSUE TITLE
Track API usage in the back-end

### ISSUE THREAD

**Issue by nikosdion** [akeeba/akeebasubs#254]
We are missing a way to track coupon API usage from the back-end of the merchant's site. Please implement this feature. Ideally, the grid view would show percent and available value (available # of coupons, available # of subscriptions, available amount of money).

**Comment by tampe125** [comment]
Moreover I think we should add a "note" field in the API table. Here we should store additional, useful info.
For example reseller customer details (ID, email, name/last name): this could be useful if anything goes wrong and we need to double check and cross-reference the data.

**Comment by nikosdion** [comment]
I agree
