### ISSUE TITLE
Error When Updating User Account Information

### ISSUE THREAD

**Issue by bryanearl** [akeeba/akeebasubs#256]
This problem has been an issue since upgrading to version 5.  I just downloaded and installed the newest version (5.0.4) today in hopes of it fixing the problem but unfortunately it did not.  Everything throughout the site seems to work properly except for when the user goes to the "My Member Profile / userinfo" area and tries to update the information in any way. The error happens if no information is changed as well, if the user clicks the "UPDATE USER INFORMATION" button at all it throws the error.  Please see the screenshot for the error:

![update-info-error](https://cloud.githubusercontent.com/assets/15130453/12705102/ba5415f2-c816-11e5-8450-b2fe7f7eaf5c.PNG)

**Comment by nikosdion** [comment]
I can't reproduce that. Also taking a look at the layout of the page it seems like you've done a template override? If you can trace it to a specific validation rule we can do more testing.
