### ISSUE TITLE
Not possible to subscribe to a level with a similar slug to another level

### ISSUE THREAD

**Issue by chivitli** [akeeba/akeebasubs#259]
Imagine you have two levels where one has slug 'awesome-akeeba-subs' and another with 'akeeba-subs'. When trying to create a new subscription on the frontend, if 'awesome-akeeba-subs' is the first one in the db, it will be shown even when trying to subscribe to 'akeeba-subs'. The reason is that the slug is searched using a partial and not the exact search, instead of
```
`slug` LIKE '%akeeba-subs%'
```
should be
```
`slug` LIKE 'akeeba-subs'
```
in the query

However, I was unable to debug it completely, I'm not sure where to mark slug to be searched using exact instead of partial matching.

**Comment by nikosdion** [comment]
I have tried to reproduce this with the latest development branch of Akeeba Subscriptions and FOF 3 but it's impossible to reproduce.

**Comment by chivitli** [comment]
I am using version 5.0.5 (upgraded from version 4 though). I will make a clean install and test again

**Comment by chivitli** [comment]
I managed to reproduce it on a clean install as well.

Steps:
1) Clean Joomla install + Akeeba Subs 5.0.5
2) Setup subscription level called "Awesome Akeeba Subs"
3) Setup subscription level called "Akeeba Subs"
4) Create a menu item for specific level for "Awesome Akeeba Subs"
5) Create a menu item for specific level for "Akeeba Subs"
6) Navigate to "Akeeba Subs" menu

Result: Subscription for "Awesome Akeeba Subs"
Expected: Subscription for "Akeeba subs"

**Comment by nikosdion** [comment]
Yes, I figured that out too. The original instructions were a bit off. You need to create the record with the longest name (e.g. "level-plus") _before_ the record with the shorter name (e.g. "level") and then try to access the level with the shorter name. Commit b4fb492 fixes that.

**Comment by chivitli** [comment]
Yeah, sorry for the confusion. I checked the fix, works great! You were incredibly quick, thanks! :+1:

**Comment by nikosdion** [comment]
Thank you for the heads up :)
