### ISSUE TITLE
Import function in 3.5/PHP7 broken

### ISSUE THREAD

**Issue by blueforce** [akeeba/akeebasubs#264]
hi Nik
I get this Error, when I try to use the import function:
"Model Tools could not fetch column list for the table #__akeebasubs_tools"

steps to reproduce:
go to components > akkeba subs > dashboard and click the import button, the failure appears

tested with J! 3.5 rc4 and PHP 7.0.4

cheers

**Comment by tampe125** [comment]
Hello,

such button is a leftover from version 4, now it's completely obsolete.

Closed via d980e21975142e7ceadbc902e9cc308f9911385c
