### ISSUE TITLE
acymailing plugin not active with new users

### ISSUE THREAD

**Issue by Ruud68** [akeeba/akeebasubs#266]
Hi,
just done some extensive testing of akeebasubs in combination with acymailing plugin. Ran into the following use case:
Adding and removing a user from the selected acyba mailing lists works if the user already has an account.
If the user registers an account via the akeebasubs component (via subscribing), the account is created but the new user is NOT added to the acyba mailinglists that are configured in the subscription level.
Not much to configure so not sure if this is a configuration issue or a possible code improvement :)

**Comment by nikosdion** [comment]
If you have followed the previous discussion, I do not maintain this plugin. Someone else claimed to have updated it and it worked on his site. That's why I included it. If you are certain it doesn't work I will remove it again as it's code I have no use of and no incentive to maintain. Or you could find the issue, fix it and submit a PR – this is a developers' product after all.

**Comment by Ruud68** [comment]
Hi Thanks for the follow up. Functionality of the plugin is really usefull (for my use case), no need to remove it.
I am already looking into why it is not working for new users, but have to do a deep dive into the akeebasubs code  first to understand where to look and how to troubleshoot. Perhaps the 'original' developer of the plugin can share some thoughts on this?

**Comment by nikosdion** [comment]
The code was originally contributed by @roland-d years ago. It was reworked for Akeeba Subs 5 by @royhaanen in January 2016. I guess you need to contact Roy about it.

**Comment by Ruud68** [comment]
Hi, thanks for the follow up.
Been trying to get this to work but suspect that the culprit is in acyba and what happens when a new user is created. In acyba you can configure to automatically add new user to mailinglists. This works even when account creation is done via Akeebasubs. What I suspect is that acyba sets only the configured lists (and not the lists added via the api) and when no auto subscriptions are configured in acyba, leave them empty.

I posted a topic over on the acyba forum: https://www.acyba.com/forum/5-acymailing-how-to/73920-adding-list-to-user-via-api.html#96647

I @royhaanen or @roland-d have any ideas, please feel free to chime in :)

**Comment by royhaanen** [comment]
Hi @Ruud68, on my website www.roosterz.nl the users are added to a mailing list when they register using the akeebasubs component so I can't reproduce this issue. 

Perhaps the issue is in your acymaling settings? What are your settings wrt Acymailing Configuration->Subscription?

**Comment by Ruud68** [comment]
Hi Roy,

Thanks for the follow up: just solved it :)
My subscription adds the subscriber to the Joomla! author group, in acymailing I have an 'blogger' list specially for this group > I have set an ACL on that list so only authors can subscribe and no other users.

It turns out that this is the source of the problem.

When a new user registers he is member of the group registered, after payment the acymailing plugin adds this new user to the blogger list BEFORE akeeba subs adds the user to the Author group.
This results in the 'error' as stated in the original post.

Why it does work for existing users I don't know. Apparently they are first added to the joomla group before they are subscribed to the acymailing list.

Removing the ACL on the acymailing list 'blogger' did the trick, now just have to figure out how to prevent others from viewing / subscribing to this list.

So for now closing this one :)

Thanks all for your help!
