### ISSUE TITLE
SQL Error: ALTER TABE `#__akeebasubs_levels` DROP KEY `slug`;

### ISSUE THREAD

**Issue by svenbluege** [akeeba/akeebasubs#268]
I just updated to 5.1.1. If I open a url like

I get this message: 

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TABE `#__akeebasubs_levels` DROP KEY `slug`' at line 1 SQL=ALTER TABE `#__akeebasubs_levels` DROP KEY `slug`;`

**Comment by nikosdion** [comment]
Be a developer, check the repository. Tip: already fixed. Pro tip: This is marked NO SUPPORT. I will delete the repository today, I've had enough of these questions. Fork while you can.
