### ISSUE TITLE
Joomla - Akeeba Subscription

### ISSUE THREAD

**Issue by joomsite** [akeeba/akeebasubs#282]
Hello,

 can't create new Subscription as we must select User to create new subscription, but I can't do that.

I click on the user to select that user but nothing happned. I can't select User. I tried in different browser as well. Chrome, Fire Fox and IE- didn't work any where. Can't go back to form with user selected.

![image](https://cloud.githubusercontent.com/assets/7931557/24962830/eaa4d292-1f94-11e7-8e6b-ac0572c3cfae.png)

![image](https://cloud.githubusercontent.com/assets/7931557/24963005/5ef12240-1f95-11e7-80ad-2caa149e3751.png)

**Comment by nikosdion** [comment]
Tried with: Google Chrome (Windows, macOS, Linux); Firefox (Windows, macOS, Linux); Opera (Windows); Safari (macOS). The link works great. Check your third party Javascript on the page. This is not an issue with Akeeba Subscriptions.
