### ISSUE TITLE
Build fails on package-fof

### ISSUE THREAD

**Issue by tassosm** [akeeba/akeebasubs#290]
I get the following errors while creating a dev release.

```
AkeebaSubscriptions > package-fof:

[PHP Error] chdir(): No such file or directory (errno 2) [line 94 of /var/www/akeeba/buildfiles/phing/tasks/GitVersionTask.php]
[PHP Error] chdir(): No such file or directory (errno 2) [line 111 of /var/www/akeeba/buildfiles/phing/tasks/GitDateTask.php]
    [phing] Basedir /var/www/akeeba/akeebasubs/build does not exist

BUILD FAILED
/var/www/akeeba/akeebasubs/build/../../buildfiles/phing/common.xml:804:12: /var/www/akeeba/akeebasubs/build/../../buildfiles/phing/common.xml:808:20: /var/www/akeeba/akeebasubs/build/../../buildfiles/phing/common.xml:827:46: Directory /var/www/akeeba/akeebasubs/build/../../fof3/release not found.

```

I've initialized the repo with php ../buildfiles/tools/link.php `pwd`
I've linked it with phing link
I've built both FOF and Strapper before creating the dev release
All repos are updated

Any help would be appreciated.

**Comment by nikosdion** [comment]
The rewritten buildfiles repository requires to go in there first and do a `composer init`. Then make sure you have the folders `akeebasubs` (this repo), `fof` (FOF 3, development branch) and `buildfiles` (master branch) as described in the README.
