### ISSUE TITLE
Documentation directory

### ISSUE THREAD

**Issue by machadoug** [akeeba/akeebasubs#300]
Greetings,

The readme file says:

> This builds the documentation in PDF format using the DocBook XML sources found in the **_documentation directory_**.

Can you please provide the Documentation directory, the PDF or a Documentation Link (even if outdated)?

Thanks in advance.

**Comment by nikosdion** [comment]
The documentation has been migrated to the Wiki of this repository. Please look at the top of the repository’s page on Github and click on Wiki. GitHub also provides a Git repository with the Wiki source in Markdown format.
