### ISSUE TITLE
Days remaining template placeholder

### ISSUE THREAD

**Issue by demis-palma** [akeeba/akeebasubs#302]
Looking at both the source code and the wiki, it seems that expiration email notifications don't provide a variable which indicates the number of days remaining to the expiration.
I mean something like this:
`Your subscription will expire in [DAYS_REMAINING] days.`

I guess that this particular variable can be implemented by a third party plug-in through the event "onAkeebasubsAfterProcessTags" but I just wanted a confirmation that such feature does not exist yet.

Otherwise, if implemented directly into the main source, are there any change that the PR will be merged?

**Comment by nikosdion** [comment]
Sorry, I have completely missed this issue! This is correct, we do not provide such a variable. It is currently not possible to add more tags with a plugin. If you make a PR with that feature I am willing to proofread it and accept it if it's an elegant solution.
