### ISSUE TITLE
Signup.js cross browser issues

### ISSUE THREAD

**Issue by sakiss** [akeeba/akeebasubs#304]
In the applyPrice function of the file: akeebasubs/component/media/js/signup.js 
, you are setting values to several input fields using the [jQuery.html()](http://api.jquery.com/html/)
```
$discountField.html(discountWithVAT.toFixed(2));
$originalField.html(originalWithVAT.toFixed(2));
```

Though the .html() is not updating the values of those inputs.
It is supposed to update the innerHTML

I suggest using the [val()](http://api.jquery.com/val/) function instead

**Comment by sakiss** [comment]
Update: The inputs for the vat, discount, total exist in my layout. I am not aware of the structure of the current default layouts

**Comment by nikosdion** [comment]
These fields are `<span>`s in the templates shipped with Akeeba Subscriptions. Therefore using `.html()` is the correct behaviour. Using `val()` on a `<span>` is an error.

When you make a template override which deviates significantly from the defaults, e.g. removes / changes elements or their classes / IDs, you have to override the JavaScript as well. Do remember that Akeeba Subscriptions is based on the FOF framework which brought media overrides to Joomla several years before Joomla itself offered this as a core feature :)
