### ISSUE TITLE
Flickering company form fields on subscription form page.

### ISSUE THREAD

**Issue by UWiX-nl** [akeeba/akeebasubs#306]
Using Joomla! 3.8.6 and Akeeba Subscriptions v6.0.0 with no template overrides to be sure. Notice the following when a guest user wants to subscribe to a license (view=level) in the frontend:

The forms opens correctly and "Purchasing as a company" is set to "No" by default. The corresponding company fields are hidden at first glance.
A takes a few seconds before the payment method and "Subscribe now!" button appear; when this happends the company fields are unhidden - even when no selection is made or no information is typed yet.
Switching the "Purchasing as a company" field to 'Yes' and back to 'No' hides the company fields again. But after a few seconds they appear again. 

The "Total Charge" amount which should show the price including taxes when "Purchasing as a company" is set to 'No' doesn't change back according the choice.

**Comment by nikosdion** [comment]
Feel free to provide a Pull Request.
