### ISSUE TITLE
Automatic enabling of subscription no longer working after migrating to 6.0.0

### ISSUE THREAD

**Issue by corejoomla** [akeeba/akeebasubs#310]
After migrating to v6.0.0, the PayPal payments are no longer activated automatically. It needs to be enabled manually.

- No new plugins enabled or disabled
- PayPal plugin is enabled as in earlier version
- No change was done from working version (v5) to current, except upgrading to v6

**Comment by svenbluege** [comment]
You mean like after a successful payment? Did you checked the PayPal logs in [administrator]/logs/?

**Comment by nikosdion** [comment]
This plugin is used on our site, for the bulk of our subscriptions. It definitely works. You most likely have a very old callback URL (in v6 we dropped support for the legacy callback URL format we were carrying from v2) or your server does not support TLS 1.2 which PayPal now requires (irrespective of the Akeeba Subscriptions version you are using).

**Comment by corejoomla** [comment]
Thanks a lot for the answers. Checked it, TLS 1.0, 1.1 and 1.2 are supported and using the following url as per documentation.

`https://www.mysite.com/index.php?option=com_akeebasubs&view=callback&paymentmethod=paypal`

Any other pointers where I can verify it?

**Comment by nikosdion** [comment]
As @svenbluege told you, check the log file. If there is no log entry it means that PayPal is unable to contact your server.

Otherwise check the log file and see why the payment notification is being declined. The reason for rejecting the IPN is written in the log.

**Comment by codealfa** [comment]
I've been having the same trouble so I've been troubleshooting this. I wasn't getting any logs in the akpayment_paypal_ipn.php file but when I checked the IPN history in PayPal it shows where the IPN was sent and the response code was 200. 

After further troubleshooting I noticed in the PayPal payment plugin on line 128 in the paypal.php file, the callback function is defined as: `public function onAKPaymentCallback($paymentmethod, $data)`.
However the `$paymentmethod` variable is coming over as an empty string so I changed line 133 from `if ($paymentmethod != $this->ppName)` to `if ($data['paymentmethod'] != $this->ppName)` and it is now working. I don't know if this is a bug but you can see if this works for you. I'll keep this fix until further light is shed on the situation or I can figure out exactly what is going on.

I'm only using the PayPal payment plugin on my site at the moment so I don't know if that makes any difference as to why this is working for some but not others.

**Comment by corejoomla** [comment]
Thank you @codealfa, I can confirm that it is working with that code change.

**Comment by nikosdion** [comment]
The change is **wrong**. I had written a very long email yesterday explaining why this happens but the computer crashed. Anyway, the code to fix it is in this commit https://github.com/akeeba/akeebasubs/commit/b28f7ae98f75b4533863af1f99cc4985a7a26c65

**Comment by nikosdion** [comment]
The FEF repo is private, only the downloads are public. You can simply run `phing git -Dversion=6.0.1.dev180406` to have the build scripts fetch the latest _published_ versions of FOF and FEF. The idea is that when you define a numbered version it doesn't try to build FEF and FOF, it tries to download them. By using a dev and current date suffix you make this into a version which can be installed, it won't notify you of updates for the previous stable but _will_ notify you of updates to the next stable (6.0.1) since Joomla is using [version_compare](http://php.net/version_compare) to decide the update availability.

**Comment by codealfa** [comment]
Still didn't work but that's ok. I'll just continue to do it my way since the downloads are available and the end results are the same. At least now I don't have that annoying notification to update to the previous stable so that's a plus.
