### ISSUE TITLE
Unable to view or edit user account from subscriptions page in backend

### ISSUE THREAD

**Issue by corejoomla** [akeeba/akeebasubs#312]
Issue: When you click on the user name in subscriptions page, instead of showing user details it shows users listing page with an error message "Cannot lock a record which has not been loaded". Further clicking on any user link in users listing page shows new user form.

Steps to reproduce it:
1. Go to the subscriptions page
2. Click on username link of any subscription row

Version: 6.0.0

**Comment by nikosdion** [comment]
This has already been fixed. Please try actually using the latest development branch because you keep reporting issues I've fixed ;)
