### ISSUE TITLE
Opening a subscription to mark payment complete then saving creates a NEW subscription 

### ISSUE THREAD

**Issue by StarAzure** [akeeba/akeebasubs#314]
When I open a subscription, change payment to complete, that item is not affected but it creates a new copy of that item. It should mark the item I opened as published instead of creating a new copy of that item and publishing it.

**Comment by nikosdion** [comment]
This has already been fixed but I didn’t have time to publish a new release. You can build one yourself using the README instructions.

**Comment by StarAzure** [comment]
Ok I will try. Will it also fix the coupons duplicating when saved ?

**Comment by StarAzure** [comment]
Issue fixed in 6.1.
