### ISSUE TITLE
Custom fileds did not save anywhere

### ISSUE THREAD

**Issue by rauschr** [akeeba/akeebasubs#320]
Hi,
I use Agree to EU terms, but did not save fileds anywhere.

What can I do?

**Comment by nikosdion** [comment]
It saves it to the User's profile in Akeeba Subscriptions. I can tell you that as a fact since I've been using this for months on my own site.

**Comment by rauschr** [comment]
I see, but I create a new custom field.
I would like to save to subscription, not to user. My service is hosting.
I would like to find onBeforeSave event.
