### ISSUE TITLE
Disable Country & Invoicing

### ISSUE THREAD

**Issue by Mestnij** [akeeba/akeebasubs#321]
Nicholas greetings to you from Russia!
Please tell me how to disable the subscription payment page:
**Country information
Invoicing information**
I am grateful for the answer.

**Comment by ggtatarin** [comment]
Too interests me. Thanks in advance.

**Comment by nikosdion** [comment]
We actually _removed_ this feature because it made no sense for us. Moreover, it complicated the validation code (PHP and JavaScript), making it very unreliable under some circumstances. We are not interested in re-implementing this feature.
