### ISSUE TITLE
User-Profile-Sync plugin manual page but no plugin?

### ISSUE THREAD

**Issue by Marvino-il-Marziano** [akeeba/akeebasubs#324]
Hi --

The quickstart/manual speaks about a plugin that doesn't seem to exist anymore? Or not yet?

https://github.com/akeeba/akeebasubs/wiki/Joomla%21-User-Profile-Sync

[I'm using the 6.1.4 release because I've not yet got my own Build to work.]

I didn't find any info on changes to this Sync plugin, on the Releases page. I also don't remember this plugin from the version I was experimenting with a year ago; I seem to remember making my own plugin that then populated normal J User - Profile plugin and having the manual explain it. [I tried installing various old versions on a downgraded Joomla, but then I found myself far from home.]

For me personally, that kind of integration is vital as it's a society membership site I'm working on. I understand I cannot bribe anyone into offering support, but I'm trying to make sense of the existing documentation.

**Comment by nikosdion** [comment]
This plugin has been removed since Akeeba Subscriptions 5.2.0 released on October 8th, 2016.
