### ISSUE TITLE
Level Group can't be set

### ISSUE THREAD

**Issue by royroosterz** [akeeba/akeebasubs#325]
In version 6.1.4. the Level Group can't be changed for a subscription level. 

I have defined two Level Groups. When I create a subscription level and try to assign a Level Group to it the page refreshes and no Level Group is selected again, see attached screen recording. 

Also when trying to edit a Level Group itself the name is not included in the Title field and the published field is set to "No".

[Screen Recording 2019-01-04 at 17.04.29.mov.zip](https://github.com/akeeba/akeebasubs/files/2727591/Screen.Recording.2019-01-04.at.17.04.29.mov.zip)

**Comment by nikosdion** [comment]
There was a missing property in the field definition to prevent this behavior. Thank you for the heads up!
