### ISSUE TITLE
akeeba.fef.tabs() never called

### ISSUE THREAD

**Issue by nickkraakman** [akeeba/akeebasubs#385]
When trying to set up a new subscription level, I was unable to navigate to the next tab. After a _lot_ of debugging, it turned out `akeeba.fef.tabs();` is never called.

The Akeebasubs code contains:

```
window.addEventListener('DOMContentLoaded', function(event) {
	akeeba.fef.tabs();
});
```

And this snippet is also present in the HTML of the page, but apparently the `DOMContentLoaded` event is not properly fired.

As a workaround, I used `jQuery( document ).ready(function() { ... });` instead in the `media/fef/js/tabs.min.js` file, and then the tabs worked.

**Comment by nikosdion** [comment]
Which browser are you using? I have not been able to reproduce this on MacOS Mojave or Kubuntu 19.04 using the latest versions of Chrome, Opera, Firefox or Safari (macOS only).

Another question. How's your network connection to your server? Does it take a long time before the tabs.min.js file loads? I am wondering if the DOMContentLoaded event has fired before the tabs JS has loaded.

**Comment by nickkraakman** [comment]
Hi @nikosdion, I used Chrome 75.0.3770.100 and Safari 12.1.1 on MacOS Mojave.

According to the network tab, it takes 2s to connect to the server, then the `tab.min.js` file loads in 1.44s. The site runs on Bluehost, so is not the fastest, although it uses the Cloudflare CDN to speed things up.

**Comment by nikosdion** [comment]
Here's the thing. We normally add loading of tab.min.js in the HTML head to prevent the DOM loaded event firing before that JS file is loaded. However, it's possible that you have a third party plugin which moves the JS files to the bottom of the page, or you're using CloudFlare's RocketLoader. In both cases third party code does something idiotic we cannot prevent without A LOT of pain (trust me, I've applied the workaround in Akeeba Backup).

However and as explained in the README, Akeeba Subscriptions is an internal project. We are writing it to work on our site. It's not mass distributed software. I have no reason to add a complicated workaround for an issue which doesn't affect our site. Sorry :(

**Comment by nickkraakman** [comment]
Hi @nikosdion, thanks for your reply, and I fully understand it is an internal project, just wanted to share the issue nevertheless.

RocketLoader is indeed used, so that could be it. I would think that if `tab.min.js` was not loaded until _after_ the `DOMContentLoaded` event was fired, a `call to undefined function` error would appear though.

Anyways, thanks again for the reply and have a great day!
