### ISSUE TITLE
Tracking Google Analytics when using Paypal

### ISSUE THREAD

**Issue by parthlawate** [akeeba/akeebasubs#64]
This link shows a way to correct the attribution for Ecommerce analytics in Google for Paypal transactions. Right now all transactions show the referrer as Paypal instead of the correct one.. 

http://support.americommerce.com/hc/en-us/articles/201903670-How-to-properly-track-orders-in-Google-Analytics-when-you-accept-PayPal-as-a-method-of-payment 

Does anyone know if there is a standard return url we can set in Paypal ? Note that this not the notification url .. but the return one..

**Comment by nikosdion** [comment]
Sorry, I missed the notification of this issue (which is really not an issue). You need to edit plugins/akpayment/paypal/paypal.php line 64 to read:
```php
'success'		=> $rootURL.str_replace('&amp;','&',JRoute::_('index.php?option=com_akeebasubs&view=message&slug='.$slug.'&layout=order&subid='.$subscription->akeebasubs_subscription_id . '&utm_nooverride=1')),
```
As you can see in plugins/akpayment/paypal/paypal/form.php line 13 this is where the return URL comes from.

**Comment by parthlawate** [comment]
Thanks Nic !

Will try the patch. However not sure why you think its not an issue ? Instead of say Extensions.joomla.org showing up as the referrer for the sale, i end up seeing paypal in Google analytics.

**Comment by nikosdion** [comment]
It's an issue with Google Analytics, not Akeeba Subscriptions or Joomla!. Google gives you a proprietary workaround which I'm not willing to add as the default option because, well, it's proprietary! There is a better solution called "cookies" but it stumbles on the idiotic EU laws which are also not an issue coming from our software. So no, really, it's not an issue for me.

**Comment by parthlawate** [comment]
Yes definitely its a google analytics issue :) How about adding a param for it it ? Maybe make it general by saying url params to add to success url or something so that its not google analytics specific ..

**Comment by nikosdion** [comment]
You can always fork the plugin and modify the line I told you.

**Comment by parthlawate** [comment]
Ok will do ! Thank you :+1:
