### ISSUE TITLE
Validation of the new EU checkboxes.

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#87]
Hey guys,
When you submit the form for the first time a JS validation of the fields kicks in. Whenever I check any of the checkboxes the "please confirm to continue" text dissapears and then appears again a second after the validation is complete. The same happens with the TOS.
You can recreate the issue on your sub page as well: https://www.akeebabackup.com/subscribe/new/atpro.html?layout=default

**Comment by nikosdion** [comment]
I know. I won't debug for a few days to weeks. It is very low priority for me. Care to debug yourself?=
