### ISSUE TITLE
Can we add the tax rate in the form?

### ISSUE THREAD

**Issue by compojoom** [akeeba/akeebasubs#88]
Hey guys,
I just hacked the signup.js to show the current tax rate:
https://compojoom.com/subscriptions/hotspots/new/hotspots12

Can we add this as standard? Due to new EU laws each customer is going to see a different tax, it would be good to show him the applied tax rate. We have the information anyway from the ajax response.
All I did was - update the applyPrice and I added
```
$('#akeebasubs-sum-taxrate').html(response.taxrate);
```

in the html I added:
```
<label class="control-label col-sm-2">
				<?php echo JText::_('COM_AKEEBASUBS_LEVEL_SUM_VAT')?>
				<small>(<span id="akeebasubs-sum-taxrate">0</span>&percnt; VAT)</small>
			</label>
```

**Comment by nikosdion** [comment]
I agree, we can do that. Care to submit a PR so that we can credit this feature to you?

**Comment by compojoom** [comment]
Just wanted to add this, but found out that it is already in. Thanks!

**Comment by nikosdion** [comment]
I had some spare time today after lunch after all ;)
