### ISSUE TITLE
random same users being removed from groups

### ISSUE THREAD

**Issue by dedicaid** [akeeba/akeebasubs#89]
has random same users being removed from groups daily been an issue here? started noticing it after 4 update was 1 person then 2 now 3 over the course of a few months . its a very small amount of people vs overall subscriptions less than 1% . any thoughts appreciated . thanks

**Comment by nikosdion** [comment]
If by "random" you mean "people whose subscriptions are expiring" then yes, it's how the component has been designed since its first release some 4 years ago. Other than that, no, this doesn't happen.

**Comment by dedicaid** [comment]
no that would be silly i mean before expiration mid subscription even re added manually to the group they are removed again next day , only a few users with nothing in common are having this happen . i am not sure if it is a akeeba issue or something else messing with it .

**Comment by nikosdion** [comment]
Our code is only triggered when the status of the subscription changes, i.e. when a subscription becomes active (published) or disabled (unpublished). If you see the subscription status change then it is triggered by our code. A subscription can become disabled for two reasons: it expires or the payment is canceled/refunded and the payments provider notifies your site. If the status doesn't change the problem is elsewhere.

**Comment by dedicaid** [comment]
i suspect its ipn , possible conflict with another paypal button elsewhere . but no the status does not change within the subscriptions admin area just the user area groups . thank you

**Comment by nikosdion** [comment]
If the status doesn't change it's not the IPN. If it was the IPN the sequence of events is: IPN sent – the plgAkpaymentPaypal plugin is triggered – the subscription status is changed and the subscription is saved – the plgAkeebasubsJoomla plugin (onAKUserRefresh method, called by the onAKSubscriptionChange event in plgAkeebasubsAbstract) is triggered – the user is added/removed from user groups. If the status doesn't change the AkeebasubsTableSubscription class doesn't trigger the  onAKSubscriptionChange event. And even if you trigger this event manually plgAkeebasubsAbstract::loadUserGroups would return the same list of groups to add the user to, therefore the onAKUserRefresh method would perform no change.

**Comment by dedicaid** [comment]
thanks, if i learn anything relevant to you  i will keep you posted .
