### ISSUE TITLE
Subscription detail will display the custom field "Subscription options" field type 

### ISSUE THREAD

**Issue by photodude** [akeeba/akeebasubs#97]
Subscription detail displays an editable field for the custom field "Subscription options" field type. Since Subscription options custom field type "can increase or decrease the net price and the duration (length in days) of the subscription" the user should not be able to see this field in the details or should not be able to edit this field. 

Replication steps
1.	Create new subscription level with default settings 30 days length, 50 for price
2.	Create a new custom field with: “when to show” set to the specific new subscription and of type "Subscription options"
3.	Add options to the custom field according to documentation convention VALUE=LABEL|PRICE|DAYS
I used the following to test
1=add 30 days|35|30
2=only 15 days|-10|-15
4.	Add a subscription to a user
5.	Review in front end from menu type (Akeeba Subscriptions » All of my subscriptions)
6.	Select the “view details” action (button) in the front end
7.	Under “Subscription preferences” there is an editable field for the custom field "Subscription options" field type which was added. 
8.	Note: the user can select a subscription option, but the option will not update the subscription. The user will properly given the error “Please check your data” if the user attempts to “Update subscription details” after selecting an option.

**Comment by nikosdion** [comment]
This can't change without doing a heck of a lot of changes in the entire custom fields implementation throughout the component. That's way too much work for what is just a display issue (you can't change anything by selecting a different option here). I will close this as won't fix.
